#include "SexyAppFramework/ResourceManager.h"
#include "SexyAppFramework/Font.h"
#include "Res.h"

using namespace Sexy;

#pragma warning(disable:4311 4312)

static bool gNeedRecalcVariableToIdMap = false;

bool Sexy::ExtractResourcesByName(ResourceManager* theManager, const char* theName)
{
	if (strcmp(theName, "Init") == 0) return ExtractInitResources(theManager);
	if (strcmp(theName, "LoadingThread") == 0) return ExtractLoadingThreadResources(theManager);
	if (strcmp(theName, "Register") == 0) return ExtractRegisterResources(theManager);
	return false;
}

Sexy::ResourceId Sexy::GetIdByStringId(const char* theStringId)
{
	typedef std::map<std::string, int> MyMap;
	static MyMap aMap;
	if (aMap.empty())
	{
		for (int i = 0; i < RESOURCE_ID_MAX; i++)
			aMap[GetStringIdById(i)] = i;
	}

	MyMap::iterator anItr = aMap.find(theStringId);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId)anItr->second;
}

// Init Resources
Font* Sexy::FONT_PICO129;
Font* Sexy::FONT_JUNGLEFEVER10OUTLINE;
Font* Sexy::FONT_JUNGLEFEVER17OUTLINE;
Image* Sexy::IMAGE_BLANK;
Image* Sexy::IMAGE_CURSOR_DRAGGING;
Image* Sexy::IMAGE_CURSOR_HAND;
Image* Sexy::IMAGE_CURSOR_POINTER;
Image* Sexy::IMAGE_CURSOR_TEXT;
Image* Sexy::IMAGE_LOADERBAR;
Image* Sexy::IMAGE_LOADERBARLOADING;
Image* Sexy::IMAGE_LOADERBAROVER;
Image* Sexy::IMAGE_LOADERPLAY;
Image* Sexy::IMAGE_TITLEPAGE;
Image* Sexy::IMAGE_TITLEPAGEMASK;
int Sexy::SOUND_BUTTONCLICK;

bool Sexy::ExtractInitResources(ResourceManager* theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager& aMgr = *theManager;
	try
	{
		FONT_JUNGLEFEVER10OUTLINE = aMgr.GetFontThrow("FONT_JUNGLEFEVER10OUTLINE");
		FONT_JUNGLEFEVER17OUTLINE = aMgr.GetFontThrow("FONT_JUNGLEFEVER17OUTLINE");
		IMAGE_BLANK = aMgr.GetImageThrow("IMAGE_BLANK");
		IMAGE_CURSOR_DRAGGING = aMgr.GetImageThrow("IMAGE_CURSOR_DRAGGING");
		IMAGE_CURSOR_HAND = aMgr.GetImageThrow("IMAGE_CURSOR_HAND");
		IMAGE_CURSOR_POINTER = aMgr.GetImageThrow("IMAGE_CURSOR_POINTER");
		IMAGE_CURSOR_TEXT = aMgr.GetImageThrow("IMAGE_CURSOR_TEXT");
		IMAGE_LOADERBAR = aMgr.GetImageThrow("IMAGE_LOADERBAR");
		IMAGE_LOADERBARLOADING = aMgr.GetImageThrow("IMAGE_LOADERBARLOADING");
		IMAGE_LOADERBAROVER = aMgr.GetImageThrow("IMAGE_LOADERBAROVER");
		IMAGE_LOADERPLAY = aMgr.GetImageThrow("IMAGE_LOADERPLAY");
		IMAGE_TITLEPAGE = aMgr.GetImageThrow("IMAGE_TITLEPAGE");
		IMAGE_TITLEPAGEMASK = aMgr.GetImageThrow("IMAGE_TITLEPAGEMASK");
		SOUND_BUTTONCLICK = aMgr.GetSoundThrow("SOUND_BUTTONCLICK");
	}
	catch (ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// LoadingThread Resources
Image* Sexy::IMAGE_AA_BEAM;
Image* Sexy::IMAGE_AA_BOTTOM;
Image* Sexy::IMAGE_AA_GLOW;
Image* Sexy::IMAGE_AA_STORE;
Image* Sexy::IMAGE_AA_TOP1;
Image* Sexy::IMAGE_AA_TOP2;
Image* Sexy::IMAGE_AMP;
Image* Sexy::IMAGE_AMPCHARGE;
Image* Sexy::IMAGE_ANGIE;
Image* Sexy::IMAGE_AQUARIUM1;
Image* Sexy::IMAGE_AQUARIUM2;
Image* Sexy::IMAGE_AQUARIUM3;
Image* Sexy::IMAGE_AQUARIUM4;
Image* Sexy::IMAGE_AQUARIUM5;
Image* Sexy::IMAGE_AQUARIUM6;
Image* Sexy::IMAGE_BALLS;
Image* Sexy::IMAGE_BALROG;
Image* Sexy::IMAGE_BATTLETANKBUTTON;
Image* Sexy::IMAGE_BATTLETANKBUTTOND;
Image* Sexy::IMAGE_BILATERUS;
Image* Sexy::IMAGE_BLIP;
Image* Sexy::IMAGE_BOLT;
Image* Sexy::IMAGE_BONUS1;
Image* Sexy::IMAGE_BONUS2;
Image* Sexy::IMAGE_BONUS3;
Image* Sexy::IMAGE_BONUSAWARD;
Image* Sexy::IMAGE_BONUSAWARD2;
Image* Sexy::IMAGE_BONUSBUCKET;
Image* Sexy::IMAGE_BONUSBUTTONOVERLAY;
Image* Sexy::IMAGE_BOSS;
Image* Sexy::IMAGE_BREEDER;
Image* Sexy::IMAGE_BRINKLEY;
Image* Sexy::IMAGE_BUBBLES;
Image* Sexy::IMAGE_BUBBULATOR;
Image* Sexy::IMAGE_BUBBULATOR_STORE;
Image* Sexy::IMAGE_CENTERBUTTON;
Image* Sexy::IMAGE_CHECKED;
Image* Sexy::IMAGE_CHICKEN;
Image* Sexy::IMAGE_CHOMP;
Image* Sexy::IMAGE_CLYDE;
Image* Sexy::IMAGE_CROSSHAIR;
Image* Sexy::IMAGE_DESTRUCTOR;
Image* Sexy::IMAGE_EGGBRINKLEY;
Image* Sexy::IMAGE_EGGCRACK1;
Image* Sexy::IMAGE_EGGCRACK2;
Image* Sexy::IMAGE_EGGNOSTRADAMUS;
Image* Sexy::IMAGE_EGGPIECES;
Image* Sexy::IMAGE_EGGSHARDS;
Image* Sexy::IMAGE_EGGSTANLEY;
Image* Sexy::IMAGE_EGGWALTER;
Image* Sexy::IMAGE_ENERGYBALL;
Image* Sexy::IMAGE_EXPLOSION;
Image* Sexy::IMAGE_EXPLOSIONSMALL;
Image* Sexy::IMAGE_EXPLOSIONTINY;
Image* Sexy::IMAGE_FATBUTTON;
Image* Sexy::IMAGE_FISHBOX;
Image* Sexy::IMAGE_FISHBOXBUTTON;
Image* Sexy::IMAGE_FOOD;
Image* Sexy::IMAGE_GASH;
Image* Sexy::IMAGE_GEKKO;
Image* Sexy::IMAGE_GRUBBER;
Image* Sexy::IMAGE_GUMBO;
Image* Sexy::IMAGE_GUMBOLIGHT;
Image* Sexy::IMAGE_GUS;
Image* Sexy::IMAGE_HALO;
Image* Sexy::IMAGE_HATCHANIMATION;
Image* Sexy::IMAGE_HATCHREFLECTION;
Image* Sexy::IMAGE_HATCHSCREEN;
Image* Sexy::IMAGE_HEALTHBAR;
Image* Sexy::IMAGE_HEALTHBARTUBE;
Image* Sexy::IMAGE_HELPALIEN;
Image* Sexy::IMAGE_HELPARROW;
Image* Sexy::IMAGE_HELPPETCHOOSE;
Image* Sexy::IMAGE_HELPSCREENSAVER;
Image* Sexy::IMAGE_HELPSHELL;
Image* Sexy::IMAGE_HORZCREASE;
Image* Sexy::IMAGE_HUNGRYBREEDER;
Image* Sexy::IMAGE_HUNGRYEAT;
Image* Sexy::IMAGE_HUNGRYSWIM;
Image* Sexy::IMAGE_HUNGRYTURN;
Image* Sexy::IMAGE_ICECREAM;
Image* Sexy::IMAGE_ITCHY;
Image* Sexy::IMAGE_LASERS;
Image* Sexy::IMAGE_LASERUPGRADES;
Image* Sexy::IMAGE_LEFTBUTTON;
Image* Sexy::IMAGE_MAINBUTTON;
Image* Sexy::IMAGE_MENUBAR;
Image* Sexy::IMAGE_MENUBTND;
Image* Sexy::IMAGE_MENUBTND2;
Image* Sexy::IMAGE_MENUBTNO;
Image* Sexy::IMAGE_MENUBTNU;
Image* Sexy::IMAGE_MENUBUTTONREFLECTION;
Image* Sexy::IMAGE_MERYL;
Image* Sexy::IMAGE_MERYLBLINK;
Image* Sexy::IMAGE_MERYLLIPS;
Image* Sexy::IMAGE_MERYLTAIL;
Image* Sexy::IMAGE_MIDDLEBUTTON;
Image* Sexy::IMAGE_MIDDLEBUTTOND;
Image* Sexy::IMAGE_MINISYLV;
Image* Sexy::IMAGE_MISCITEMS;
Image* Sexy::IMAGE_MISSILE;
Image* Sexy::IMAGE_MONEY;
Image* Sexy::IMAGE_MONEYBAG;
Image* Sexy::IMAGE_MONEYFLASH;
Image* Sexy::IMAGE_NIKO;
Image* Sexy::IMAGE_NIKOTOWER;
Image* Sexy::IMAGE_NIMBUS;
Image* Sexy::IMAGE_NOSTRADAMUS;
Image* Sexy::IMAGE_OPTIONSBUTTON;
Image* Sexy::IMAGE_OPTIONSBUTTOND;
Image* Sexy::IMAGE_PEANUT;
Image* Sexy::IMAGE_PEARL;
Image* Sexy::IMAGE_PETBTNO;
Image* Sexy::IMAGE_PETBTNU;
Image* Sexy::IMAGE_PETBUTTON;
Image* Sexy::IMAGE_PETBUTTONHOLE;
Image* Sexy::IMAGE_PETBUTTONREFLECT;
Image* Sexy::IMAGE_PETBUTTONRING;
Image* Sexy::IMAGE_PETLIMITEGG;
Image* Sexy::IMAGE_PIZZA;
Image* Sexy::IMAGE_PREGO;
Image* Sexy::IMAGE_PRESTO;
Image* Sexy::IMAGE_PSYCHOSQUID;
Image* Sexy::IMAGE_RHUBARB;
Image* Sexy::IMAGE_RIGHTBUTTON;
Image* Sexy::IMAGE_RUFUS;
Image* Sexy::IMAGE_SCL_AMP;
Image* Sexy::IMAGE_SCL_ANGIE;
Image* Sexy::IMAGE_SCL_BLIP;
Image* Sexy::IMAGE_SCL_BREEDER;
Image* Sexy::IMAGE_SCL_BRINKLEY;
Image* Sexy::IMAGE_SCL_CLYDE;
Image* Sexy::IMAGE_SCL_GASH;
Image* Sexy::IMAGE_SCL_GEKKO;
Image* Sexy::IMAGE_SCL_GRUBBER;
Image* Sexy::IMAGE_SCL_GUMBO;
Image* Sexy::IMAGE_SCL_ITCHY;
Image* Sexy::IMAGE_SCL_MERYL;
Image* Sexy::IMAGE_SCL_NIKO;
Image* Sexy::IMAGE_SCL_NIMBUS;
Image* Sexy::IMAGE_SCL_NOSTRADAMUS;
Image* Sexy::IMAGE_SCL_OSCAR;
Image* Sexy::IMAGE_SCL_PREGO;
Image* Sexy::IMAGE_SCL_PRESTO;
Image* Sexy::IMAGE_SCL_RHUBARB;
Image* Sexy::IMAGE_SCL_RUFUS;
Image* Sexy::IMAGE_SCL_SEYMOUR;
Image* Sexy::IMAGE_SCL_SHRAPNEL;
Image* Sexy::IMAGE_SCL_STANLEY;
Image* Sexy::IMAGE_SCL_STARCATCHER;
Image* Sexy::IMAGE_SCL_STINKY;
Image* Sexy::IMAGE_SCL_ULTRA;
Image* Sexy::IMAGE_SCL_VERT;
Image* Sexy::IMAGE_SCL_WADSWORTH;
Image* Sexy::IMAGE_SCL_WALTER;
Image* Sexy::IMAGE_SCL_ZORF;
Image* Sexy::IMAGE_SCREENBACK;
Image* Sexy::IMAGE_SCREENTITLE;
Image* Sexy::IMAGE_SCREENTITLEHOLE;
Image* Sexy::IMAGE_SELECTORSCREEN;
Image* Sexy::IMAGE_SELECTORSPEECHBUBBLE;
Image* Sexy::IMAGE_SEYMOUR;
Image* Sexy::IMAGE_SHADOW;
Image* Sexy::IMAGE_SHELLS;
Image* Sexy::IMAGE_SHRAPNEL;
Image* Sexy::IMAGE_SIMCARNIVORE;
Image* Sexy::IMAGE_SIMEAT1;
Image* Sexy::IMAGE_SIMEAT2;
Image* Sexy::IMAGE_SIMEAT3;
Image* Sexy::IMAGE_SIMSWIM1;
Image* Sexy::IMAGE_SIMSWIM2;
Image* Sexy::IMAGE_SIMSWIM3;
Image* Sexy::IMAGE_SIMTURN1;
Image* Sexy::IMAGE_SIMTURN2;
Image* Sexy::IMAGE_SIMTURN3;
Image* Sexy::IMAGE_SLIDERTHUMB;
Image* Sexy::IMAGE_SLIDERTRACK;
Image* Sexy::IMAGE_SMALLDIE;
Image* Sexy::IMAGE_SMALLEAT;
Image* Sexy::IMAGE_SMALLSWIM;
Image* Sexy::IMAGE_SMALLTURN;
Image* Sexy::IMAGE_SMOKEMISSILE;
Image* Sexy::IMAGE_SMOKESMALL;
Image* Sexy::IMAGE_SMOKETINY;
Image* Sexy::IMAGE_SPARKLE;
Image* Sexy::IMAGE_SPARKS;
Image* Sexy::IMAGE_SPEECHBUBBLE;
Image* Sexy::IMAGE_STANLEY;
Image* Sexy::IMAGE_STARCATCHER;
Image* Sexy::IMAGE_STINKY;
Image* Sexy::IMAGE_STOREBACKDROPS;
Image* Sexy::IMAGE_STORELEFTBUTTON;
Image* Sexy::IMAGE_STORELEFTHILIGHT;
Image* Sexy::IMAGE_STORERIGHTBUTTON;
Image* Sexy::IMAGE_STORERIGHTHILIGHT;
Image* Sexy::IMAGE_STORESCREEN;
Image* Sexy::IMAGE_STORESHELL;
Image* Sexy::IMAGE_STORETOPBUTTON;
Image* Sexy::IMAGE_STORETOPHILIGHT;
Image* Sexy::IMAGE_SYLV;
Image* Sexy::IMAGE_TANKBACKDROP1;
Image* Sexy::IMAGE_TANKBACKDROP2;
Image* Sexy::IMAGE_TANKBACKDROP3;
Image* Sexy::IMAGE_TANKBACKDROP4;
Image* Sexy::IMAGE_TANKBACKDROP5;
Image* Sexy::IMAGE_TANKBACKDROP6;
Image* Sexy::IMAGE_TANKCHOOSER;
Image* Sexy::IMAGE_TANKLIGHTING;
Image* Sexy::IMAGE_TANKMASK1;
Image* Sexy::IMAGE_TANKMASK2;
Image* Sexy::IMAGE_TANKMASK3;
Image* Sexy::IMAGE_TANKMASK4;
Image* Sexy::IMAGE_TANKMASK5;
Image* Sexy::IMAGE_TANKMASK6;
Image* Sexy::IMAGE_TROPHYBAR;
Image* Sexy::IMAGE_TROPHYBUTTONS;
Image* Sexy::IMAGE_ULTRA;
Image* Sexy::IMAGE_ULYSSES;
Image* Sexy::IMAGE_UNCHECKED;
Image* Sexy::IMAGE_VERT;
Image* Sexy::IMAGE_VERTCREASE;
Image* Sexy::IMAGE_WADSWORTH;
Image* Sexy::IMAGE_WAIT_BAR;
Image* Sexy::IMAGE_WALTER;
Image* Sexy::IMAGE_WARPGLOW;
Image* Sexy::IMAGE_WARPHOLE;
Image* Sexy::IMAGE_WAVE;
Image* Sexy::IMAGE_WAVESIDE;
Image* Sexy::IMAGE_WELCOMEBACK;
Image* Sexy::IMAGE_WELCOMETO;
Image* Sexy::IMAGE_ZORF;
Image* Sexy::IMAGE_ZZZ;
int Sexy::SOUND_APPLAUSE;
int Sexy::SOUND_AWOOGA;
int Sexy::SOUND_BABY;
int Sexy::SOUND_BONUSCOLLECT;
int Sexy::SOUND_BONUSCOUNT;
int Sexy::SOUND_BUBBLES;
int Sexy::SOUND_BUY;
int Sexy::SOUND_BUZZER;
int Sexy::SOUND_CHOMP;
int Sexy::SOUND_CHOMP2;
int Sexy::SOUND_CROWNED;
int Sexy::SOUND_DIAMOND;
int Sexy::SOUND_DIE;
int Sexy::SOUND_DROPFOOD;
int Sexy::SOUND_EEL1;
int Sexy::SOUND_EEL2;
int Sexy::SOUND_EEL3;
int Sexy::SOUND_EVILLAFF;
int Sexy::SOUND_EXPLODE;
int Sexy::SOUND_EXPLOSION1;
int Sexy::SOUND_EXPLOSION4;
int Sexy::SOUND_FART;
int Sexy::SOUND_FART2;
int Sexy::SOUND_GROW;
int Sexy::SOUND_GUFFAW;
int Sexy::SOUND_HATCH;
int Sexy::SOUND_HEAL;
int Sexy::SOUND_HIT;
int Sexy::SOUND_INTERFER;
int Sexy::SOUND_MISSLE;
int Sexy::SOUND_NIKOCLOSE;
int Sexy::SOUND_NIKOOPEN;
int Sexy::SOUND_PEARL;
int Sexy::SOUND_POINTS;
int Sexy::SOUND_POINTS2;
int Sexy::SOUND_POINTS3;
int Sexy::SOUND_POINTS4;
int Sexy::SOUND_PRIMALSCREAM;
int Sexy::SOUND_PUNCH;
int Sexy::SOUND_RATTLE;
int Sexy::SOUND_RICOCHET;
int Sexy::SOUND_ROAR;
int Sexy::SOUND_ROAR2;
int Sexy::SOUND_ROAR3;
int Sexy::SOUND_SFX;
int Sexy::SOUND_SING;
int Sexy::SOUND_SLURP;
int Sexy::SOUND_SLURP2;
int Sexy::SOUND_SLURP3;
int Sexy::SOUND_SNEEZE;
int Sexy::SOUND_SONAR;
int Sexy::SOUND_SPLASH;
int Sexy::SOUND_SPLASH2;
int Sexy::SOUND_SPLASH3;
int Sexy::SOUND_SPLASHBIG;
int Sexy::SOUND_TAPGLASS;
int Sexy::SOUND_TONE;
int Sexy::SOUND_TONEHI;
int Sexy::SOUND_TONELO;
int Sexy::SOUND_TONESUPERHI;
int Sexy::SOUND_TREASURE;
int Sexy::SOUND_UNLEASH;
int Sexy::SOUND_ZAP;
int Sexy::SOUND_ZZAM;

bool Sexy::ExtractLoadingThreadResources(ResourceManager* theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager& aMgr = *theManager;
	try
	{
		IMAGE_AA_BEAM = aMgr.GetImageThrow("IMAGE_AA_BEAM");
		IMAGE_AA_BOTTOM = aMgr.GetImageThrow("IMAGE_AA_BOTTOM");
		IMAGE_AA_GLOW = aMgr.GetImageThrow("IMAGE_AA_GLOW");
		IMAGE_AA_STORE = aMgr.GetImageThrow("IMAGE_AA_STORE");
		IMAGE_AA_TOP1 = aMgr.GetImageThrow("IMAGE_AA_TOP1");
		IMAGE_AA_TOP2 = aMgr.GetImageThrow("IMAGE_AA_TOP2");
		IMAGE_AMP = aMgr.GetImageThrow("IMAGE_AMP");
		IMAGE_AMPCHARGE = aMgr.GetImageThrow("IMAGE_AMPCHARGE");
		IMAGE_ANGIE = aMgr.GetImageThrow("IMAGE_ANGIE");
		IMAGE_AQUARIUM1 = aMgr.GetImageThrow("IMAGE_AQUARIUM1");
		IMAGE_AQUARIUM2 = aMgr.GetImageThrow("IMAGE_AQUARIUM2");
		IMAGE_AQUARIUM3 = aMgr.GetImageThrow("IMAGE_AQUARIUM3");
		IMAGE_AQUARIUM4 = aMgr.GetImageThrow("IMAGE_AQUARIUM4");
		IMAGE_AQUARIUM5 = aMgr.GetImageThrow("IMAGE_AQUARIUM5");
		IMAGE_AQUARIUM6 = aMgr.GetImageThrow("IMAGE_AQUARIUM6");
		IMAGE_BALLS = aMgr.GetImageThrow("IMAGE_BALLS");
		IMAGE_BALROG = aMgr.GetImageThrow("IMAGE_BALROG");
		IMAGE_BATTLETANKBUTTON = aMgr.GetImageThrow("IMAGE_BATTLETANKBUTTON");
		IMAGE_BATTLETANKBUTTOND = aMgr.GetImageThrow("IMAGE_BATTLETANKBUTTOND");
		IMAGE_BILATERUS = aMgr.GetImageThrow("IMAGE_BILATERUS");
		IMAGE_BLIP = aMgr.GetImageThrow("IMAGE_BLIP");
		IMAGE_BOLT = aMgr.GetImageThrow("IMAGE_BOLT");
		IMAGE_BONUS1 = aMgr.GetImageThrow("IMAGE_BONUS1");
		IMAGE_BONUS2 = aMgr.GetImageThrow("IMAGE_BONUS2");
		IMAGE_BONUS3 = aMgr.GetImageThrow("IMAGE_BONUS3");
		IMAGE_BONUSAWARD = aMgr.GetImageThrow("IMAGE_BONUSAWARD");
		IMAGE_BONUSAWARD2 = aMgr.GetImageThrow("IMAGE_BONUSAWARD2");
		IMAGE_BONUSBUCKET = aMgr.GetImageThrow("IMAGE_BONUSBUCKET");
		IMAGE_BONUSBUTTONOVERLAY = aMgr.GetImageThrow("IMAGE_BONUSBUTTONOVERLAY");
		IMAGE_BOSS = aMgr.GetImageThrow("IMAGE_BOSS");
		IMAGE_BREEDER = aMgr.GetImageThrow("IMAGE_BREEDER");
		IMAGE_BRINKLEY = aMgr.GetImageThrow("IMAGE_BRINKLEY");
		IMAGE_BUBBLES = aMgr.GetImageThrow("IMAGE_BUBBLES");
		IMAGE_BUBBULATOR = aMgr.GetImageThrow("IMAGE_BUBBULATOR");
		IMAGE_BUBBULATOR_STORE = aMgr.GetImageThrow("IMAGE_BUBBULATOR_STORE");
		IMAGE_CENTERBUTTON = aMgr.GetImageThrow("IMAGE_CENTERBUTTON");
		IMAGE_CHECKED = aMgr.GetImageThrow("IMAGE_CHECKED");
		IMAGE_CHICKEN = aMgr.GetImageThrow("IMAGE_CHICKEN");
		IMAGE_CHOMP = aMgr.GetImageThrow("IMAGE_CHOMP");
		IMAGE_CLYDE = aMgr.GetImageThrow("IMAGE_CLYDE");
		IMAGE_CROSSHAIR = aMgr.GetImageThrow("IMAGE_CROSSHAIR");
		IMAGE_DESTRUCTOR = aMgr.GetImageThrow("IMAGE_DESTRUCTOR");
		IMAGE_EGGBRINKLEY = aMgr.GetImageThrow("IMAGE_EGGBRINKLEY");
		IMAGE_EGGCRACK1 = aMgr.GetImageThrow("IMAGE_EGGCRACK1");
		IMAGE_EGGCRACK2 = aMgr.GetImageThrow("IMAGE_EGGCRACK2");
		IMAGE_EGGNOSTRADAMUS = aMgr.GetImageThrow("IMAGE_EGGNOSTRADAMUS");
		IMAGE_EGGPIECES = aMgr.GetImageThrow("IMAGE_EGGPIECES");
		IMAGE_EGGSHARDS = aMgr.GetImageThrow("IMAGE_EGGSHARDS");
		IMAGE_EGGSTANLEY = aMgr.GetImageThrow("IMAGE_EGGSTANLEY");
		IMAGE_EGGWALTER = aMgr.GetImageThrow("IMAGE_EGGWALTER");
		IMAGE_ENERGYBALL = aMgr.GetImageThrow("IMAGE_ENERGYBALL");
		IMAGE_EXPLOSION = aMgr.GetImageThrow("IMAGE_EXPLOSION");
		IMAGE_EXPLOSIONSMALL = aMgr.GetImageThrow("IMAGE_EXPLOSIONSMALL");
		IMAGE_EXPLOSIONTINY = aMgr.GetImageThrow("IMAGE_EXPLOSIONTINY");
		IMAGE_FATBUTTON = aMgr.GetImageThrow("IMAGE_FATBUTTON");
		IMAGE_FISHBOX = aMgr.GetImageThrow("IMAGE_FISHBOX");
		IMAGE_FISHBOXBUTTON = aMgr.GetImageThrow("IMAGE_FISHBOXBUTTON");
		IMAGE_FOOD = aMgr.GetImageThrow("IMAGE_FOOD");
		IMAGE_GASH = aMgr.GetImageThrow("IMAGE_GASH");
		IMAGE_GEKKO = aMgr.GetImageThrow("IMAGE_GEKKO");
		IMAGE_GRUBBER = aMgr.GetImageThrow("IMAGE_GRUBBER");
		IMAGE_GUMBO = aMgr.GetImageThrow("IMAGE_GUMBO");
		IMAGE_GUMBOLIGHT = aMgr.GetImageThrow("IMAGE_GUMBOLIGHT");
		IMAGE_GUS = aMgr.GetImageThrow("IMAGE_GUS");
		IMAGE_HALO = aMgr.GetImageThrow("IMAGE_HALO");
		IMAGE_HATCHANIMATION = aMgr.GetImageThrow("IMAGE_HATCHANIMATION");
		IMAGE_HATCHREFLECTION = aMgr.GetImageThrow("IMAGE_HATCHREFLECTION");
		IMAGE_HATCHSCREEN = aMgr.GetImageThrow("IMAGE_HATCHSCREEN");
		IMAGE_HEALTHBAR = aMgr.GetImageThrow("IMAGE_HEALTHBAR");
		IMAGE_HEALTHBARTUBE = aMgr.GetImageThrow("IMAGE_HEALTHBARTUBE");
		IMAGE_HELPALIEN = aMgr.GetImageThrow("IMAGE_HELPALIEN");
		IMAGE_HELPARROW = aMgr.GetImageThrow("IMAGE_HELPARROW");
		IMAGE_HELPPETCHOOSE = aMgr.GetImageThrow("IMAGE_HELPPETCHOOSE");
		IMAGE_HELPSCREENSAVER = aMgr.GetImageThrow("IMAGE_HELPSCREENSAVER");
		IMAGE_HELPSHELL = aMgr.GetImageThrow("IMAGE_HELPSHELL");
		IMAGE_HORZCREASE = aMgr.GetImageThrow("IMAGE_HORZCREASE");
		IMAGE_HUNGRYBREEDER = aMgr.GetImageThrow("IMAGE_HUNGRYBREEDER");
		IMAGE_HUNGRYEAT = aMgr.GetImageThrow("IMAGE_HUNGRYEAT");
		IMAGE_HUNGRYSWIM = aMgr.GetImageThrow("IMAGE_HUNGRYSWIM");
		IMAGE_HUNGRYTURN = aMgr.GetImageThrow("IMAGE_HUNGRYTURN");
		IMAGE_ICECREAM = aMgr.GetImageThrow("IMAGE_ICECREAM");
		IMAGE_ITCHY = aMgr.GetImageThrow("IMAGE_ITCHY");
		IMAGE_LASERS = aMgr.GetImageThrow("IMAGE_LASERS");
		IMAGE_LASERUPGRADES = aMgr.GetImageThrow("IMAGE_LASERUPGRADES");
		IMAGE_LEFTBUTTON = aMgr.GetImageThrow("IMAGE_LEFTBUTTON");
		IMAGE_MAINBUTTON = aMgr.GetImageThrow("IMAGE_MAINBUTTON");
		IMAGE_MENUBAR = aMgr.GetImageThrow("IMAGE_MENUBAR");
		IMAGE_MENUBTND = aMgr.GetImageThrow("IMAGE_MENUBTND");
		IMAGE_MENUBTND2 = aMgr.GetImageThrow("IMAGE_MENUBTND2");
		IMAGE_MENUBTNO = aMgr.GetImageThrow("IMAGE_MENUBTNO");
		IMAGE_MENUBTNU = aMgr.GetImageThrow("IMAGE_MENUBTNU");
		IMAGE_MENUBUTTONREFLECTION = aMgr.GetImageThrow("IMAGE_MENUBUTTONREFLECTION");
		IMAGE_MERYL = aMgr.GetImageThrow("IMAGE_MERYL");
		IMAGE_MERYLBLINK = aMgr.GetImageThrow("IMAGE_MERYLBLINK");
		IMAGE_MERYLLIPS = aMgr.GetImageThrow("IMAGE_MERYLLIPS");
		IMAGE_MERYLTAIL = aMgr.GetImageThrow("IMAGE_MERYLTAIL");
		IMAGE_MIDDLEBUTTON = aMgr.GetImageThrow("IMAGE_MIDDLEBUTTON");
		IMAGE_MIDDLEBUTTOND = aMgr.GetImageThrow("IMAGE_MIDDLEBUTTOND");
		IMAGE_MINISYLV = aMgr.GetImageThrow("IMAGE_MINISYLV");
		IMAGE_MISCITEMS = aMgr.GetImageThrow("IMAGE_MISCITEMS");
		IMAGE_MISSILE = aMgr.GetImageThrow("IMAGE_MISSILE");
		IMAGE_MONEY = aMgr.GetImageThrow("IMAGE_MONEY");
		IMAGE_MONEYBAG = aMgr.GetImageThrow("IMAGE_MONEYBAG");
		IMAGE_MONEYFLASH = aMgr.GetImageThrow("IMAGE_MONEYFLASH");
		IMAGE_NIKO = aMgr.GetImageThrow("IMAGE_NIKO");
		IMAGE_NIKOTOWER = aMgr.GetImageThrow("IMAGE_NIKOTOWER");
		IMAGE_NIMBUS = aMgr.GetImageThrow("IMAGE_NIMBUS");
		IMAGE_NOSTRADAMUS = aMgr.GetImageThrow("IMAGE_NOSTRADAMUS");
		IMAGE_OPTIONSBUTTON = aMgr.GetImageThrow("IMAGE_OPTIONSBUTTON");
		IMAGE_OPTIONSBUTTOND = aMgr.GetImageThrow("IMAGE_OPTIONSBUTTOND");
		IMAGE_PEANUT = aMgr.GetImageThrow("IMAGE_PEANUT");
		IMAGE_PEARL = aMgr.GetImageThrow("IMAGE_PEARL");
		IMAGE_PETBTNO = aMgr.GetImageThrow("IMAGE_PETBTNO");
		IMAGE_PETBTNU = aMgr.GetImageThrow("IMAGE_PETBTNU");
		IMAGE_PETBUTTON = aMgr.GetImageThrow("IMAGE_PETBUTTON");
		IMAGE_PETBUTTONHOLE = aMgr.GetImageThrow("IMAGE_PETBUTTONHOLE");
		IMAGE_PETBUTTONREFLECT = aMgr.GetImageThrow("IMAGE_PETBUTTONREFLECT");
		IMAGE_PETBUTTONRING = aMgr.GetImageThrow("IMAGE_PETBUTTONRING");
		IMAGE_PETLIMITEGG = aMgr.GetImageThrow("IMAGE_PETLIMITEGG");
		IMAGE_PIZZA = aMgr.GetImageThrow("IMAGE_PIZZA");
		IMAGE_PREGO = aMgr.GetImageThrow("IMAGE_PREGO");
		IMAGE_PRESTO = aMgr.GetImageThrow("IMAGE_PRESTO");
		IMAGE_PSYCHOSQUID = aMgr.GetImageThrow("IMAGE_PSYCHOSQUID");
		IMAGE_RHUBARB = aMgr.GetImageThrow("IMAGE_RHUBARB");
		IMAGE_RIGHTBUTTON = aMgr.GetImageThrow("IMAGE_RIGHTBUTTON");
		IMAGE_RUFUS = aMgr.GetImageThrow("IMAGE_RUFUS");
		IMAGE_SCL_AMP = aMgr.GetImageThrow("IMAGE_SCL_AMP");
		IMAGE_SCL_ANGIE = aMgr.GetImageThrow("IMAGE_SCL_ANGIE");
		IMAGE_SCL_BLIP = aMgr.GetImageThrow("IMAGE_SCL_BLIP");
		IMAGE_SCL_BREEDER = aMgr.GetImageThrow("IMAGE_SCL_BREEDER");
		IMAGE_SCL_BRINKLEY = aMgr.GetImageThrow("IMAGE_SCL_BRINKLEY");
		IMAGE_SCL_CLYDE = aMgr.GetImageThrow("IMAGE_SCL_CLYDE");
		IMAGE_SCL_GASH = aMgr.GetImageThrow("IMAGE_SCL_GASH");
		IMAGE_SCL_GEKKO = aMgr.GetImageThrow("IMAGE_SCL_GEKKO");
		IMAGE_SCL_GRUBBER = aMgr.GetImageThrow("IMAGE_SCL_GRUBBER");
		IMAGE_SCL_GUMBO = aMgr.GetImageThrow("IMAGE_SCL_GUMBO");
		IMAGE_SCL_ITCHY = aMgr.GetImageThrow("IMAGE_SCL_ITCHY");
		IMAGE_SCL_MERYL = aMgr.GetImageThrow("IMAGE_SCL_MERYL");
		IMAGE_SCL_NIKO = aMgr.GetImageThrow("IMAGE_SCL_NIKO");
		IMAGE_SCL_NIMBUS = aMgr.GetImageThrow("IMAGE_SCL_NIMBUS");
		IMAGE_SCL_NOSTRADAMUS = aMgr.GetImageThrow("IMAGE_SCL_NOSTRADAMUS");
		IMAGE_SCL_OSCAR = aMgr.GetImageThrow("IMAGE_SCL_OSCAR");
		IMAGE_SCL_PREGO = aMgr.GetImageThrow("IMAGE_SCL_PREGO");
		IMAGE_SCL_PRESTO = aMgr.GetImageThrow("IMAGE_SCL_PRESTO");
		IMAGE_SCL_RHUBARB = aMgr.GetImageThrow("IMAGE_SCL_RHUBARB");
		IMAGE_SCL_RUFUS = aMgr.GetImageThrow("IMAGE_SCL_RUFUS");
		IMAGE_SCL_SEYMOUR = aMgr.GetImageThrow("IMAGE_SCL_SEYMOUR");
		IMAGE_SCL_SHRAPNEL = aMgr.GetImageThrow("IMAGE_SCL_SHRAPNEL");
		IMAGE_SCL_STANLEY = aMgr.GetImageThrow("IMAGE_SCL_STANLEY");
		IMAGE_SCL_STARCATCHER = aMgr.GetImageThrow("IMAGE_SCL_STARCATCHER");
		IMAGE_SCL_STINKY = aMgr.GetImageThrow("IMAGE_SCL_STINKY");
		IMAGE_SCL_ULTRA = aMgr.GetImageThrow("IMAGE_SCL_ULTRA");
		IMAGE_SCL_VERT = aMgr.GetImageThrow("IMAGE_SCL_VERT");
		IMAGE_SCL_WADSWORTH = aMgr.GetImageThrow("IMAGE_SCL_WADSWORTH");
		IMAGE_SCL_WALTER = aMgr.GetImageThrow("IMAGE_SCL_WALTER");
		IMAGE_SCL_ZORF = aMgr.GetImageThrow("IMAGE_SCL_ZORF");
		IMAGE_SCREENBACK = aMgr.GetImageThrow("IMAGE_SCREENBACK");
		IMAGE_SCREENTITLE = aMgr.GetImageThrow("IMAGE_SCREENTITLE");
		IMAGE_SCREENTITLEHOLE = aMgr.GetImageThrow("IMAGE_SCREENTITLEHOLE");
		IMAGE_SELECTORSCREEN = aMgr.GetImageThrow("IMAGE_SELECTORSCREEN");
		IMAGE_SELECTORSPEECHBUBBLE = aMgr.GetImageThrow("IMAGE_SELECTORSPEECHBUBBLE");
		IMAGE_SEYMOUR = aMgr.GetImageThrow("IMAGE_SEYMOUR");
		IMAGE_SHADOW = aMgr.GetImageThrow("IMAGE_SHADOW");
		IMAGE_SHELLS = aMgr.GetImageThrow("IMAGE_SHELLS");
		IMAGE_SHRAPNEL = aMgr.GetImageThrow("IMAGE_SHRAPNEL");
		IMAGE_SIMCARNIVORE = aMgr.GetImageThrow("IMAGE_SIMCARNIVORE");
		IMAGE_SIMEAT1 = aMgr.GetImageThrow("IMAGE_SIMEAT1");
		IMAGE_SIMEAT2 = aMgr.GetImageThrow("IMAGE_SIMEAT2");
		IMAGE_SIMEAT3 = aMgr.GetImageThrow("IMAGE_SIMEAT3");
		IMAGE_SIMSWIM1 = aMgr.GetImageThrow("IMAGE_SIMSWIM1");
		IMAGE_SIMSWIM2 = aMgr.GetImageThrow("IMAGE_SIMSWIM2");
		IMAGE_SIMSWIM3 = aMgr.GetImageThrow("IMAGE_SIMSWIM3");
		IMAGE_SIMTURN1 = aMgr.GetImageThrow("IMAGE_SIMTURN1");
		IMAGE_SIMTURN2 = aMgr.GetImageThrow("IMAGE_SIMTURN2");
		IMAGE_SIMTURN3 = aMgr.GetImageThrow("IMAGE_SIMTURN3");
		IMAGE_SLIDERTHUMB = aMgr.GetImageThrow("IMAGE_SLIDERTHUMB");
		IMAGE_SLIDERTRACK = aMgr.GetImageThrow("IMAGE_SLIDERTRACK");
		IMAGE_SMALLDIE = aMgr.GetImageThrow("IMAGE_SMALLDIE");
		IMAGE_SMALLEAT = aMgr.GetImageThrow("IMAGE_SMALLEAT");
		IMAGE_SMALLSWIM = aMgr.GetImageThrow("IMAGE_SMALLSWIM");
		IMAGE_SMALLTURN = aMgr.GetImageThrow("IMAGE_SMALLTURN");
		IMAGE_SMOKEMISSILE = aMgr.GetImageThrow("IMAGE_SMOKEMISSILE");
		IMAGE_SMOKESMALL = aMgr.GetImageThrow("IMAGE_SMOKESMALL");
		IMAGE_SMOKETINY = aMgr.GetImageThrow("IMAGE_SMOKETINY");
		IMAGE_SPARKLE = aMgr.GetImageThrow("IMAGE_SPARKLE");
		IMAGE_SPARKS = aMgr.GetImageThrow("IMAGE_SPARKS");
		IMAGE_SPEECHBUBBLE = aMgr.GetImageThrow("IMAGE_SPEECHBUBBLE");
		IMAGE_STANLEY = aMgr.GetImageThrow("IMAGE_STANLEY");
		IMAGE_STARCATCHER = aMgr.GetImageThrow("IMAGE_STARCATCHER");
		IMAGE_STINKY = aMgr.GetImageThrow("IMAGE_STINKY");
		IMAGE_STOREBACKDROPS = aMgr.GetImageThrow("IMAGE_STOREBACKDROPS");
		IMAGE_STORELEFTBUTTON = aMgr.GetImageThrow("IMAGE_STORELEFTBUTTON");
		IMAGE_STORELEFTHILIGHT = aMgr.GetImageThrow("IMAGE_STORELEFTHILIGHT");
		IMAGE_STORERIGHTBUTTON = aMgr.GetImageThrow("IMAGE_STORERIGHTBUTTON");
		IMAGE_STORERIGHTHILIGHT = aMgr.GetImageThrow("IMAGE_STORERIGHTHILIGHT");
		IMAGE_STORESCREEN = aMgr.GetImageThrow("IMAGE_STORESCREEN");
		IMAGE_STORESHELL = aMgr.GetImageThrow("IMAGE_STORESHELL");
		IMAGE_STORETOPBUTTON = aMgr.GetImageThrow("IMAGE_STORETOPBUTTON");
		IMAGE_STORETOPHILIGHT = aMgr.GetImageThrow("IMAGE_STORETOPHILIGHT");
		IMAGE_SYLV = aMgr.GetImageThrow("IMAGE_SYLV");
		IMAGE_TANKBACKDROP1 = aMgr.GetImageThrow("IMAGE_TANKBACKDROP1");
		IMAGE_TANKBACKDROP2 = aMgr.GetImageThrow("IMAGE_TANKBACKDROP2");
		IMAGE_TANKBACKDROP3 = aMgr.GetImageThrow("IMAGE_TANKBACKDROP3");
		IMAGE_TANKBACKDROP4 = aMgr.GetImageThrow("IMAGE_TANKBACKDROP4");
		IMAGE_TANKBACKDROP5 = aMgr.GetImageThrow("IMAGE_TANKBACKDROP5");
		IMAGE_TANKBACKDROP6 = aMgr.GetImageThrow("IMAGE_TANKBACKDROP6");
		IMAGE_TANKCHOOSER = aMgr.GetImageThrow("IMAGE_TANKCHOOSER");
		IMAGE_TANKLIGHTING = aMgr.GetImageThrow("IMAGE_TANKLIGHTING");
		IMAGE_TANKMASK1 = aMgr.GetImageThrow("IMAGE_TANKMASK1");
		IMAGE_TANKMASK2 = aMgr.GetImageThrow("IMAGE_TANKMASK2");
		IMAGE_TANKMASK3 = aMgr.GetImageThrow("IMAGE_TANKMASK3");
		IMAGE_TANKMASK4 = aMgr.GetImageThrow("IMAGE_TANKMASK4");
		IMAGE_TANKMASK5 = aMgr.GetImageThrow("IMAGE_TANKMASK5");
		IMAGE_TANKMASK6 = aMgr.GetImageThrow("IMAGE_TANKMASK6");
		IMAGE_TROPHYBAR = aMgr.GetImageThrow("IMAGE_TROPHYBAR");
		IMAGE_TROPHYBUTTONS = aMgr.GetImageThrow("IMAGE_TROPHYBUTTONS");
		IMAGE_ULTRA = aMgr.GetImageThrow("IMAGE_ULTRA");
		IMAGE_ULYSSES = aMgr.GetImageThrow("IMAGE_ULYSSES");
		IMAGE_UNCHECKED = aMgr.GetImageThrow("IMAGE_UNCHECKED");
		IMAGE_VERT = aMgr.GetImageThrow("IMAGE_VERT");
		IMAGE_VERTCREASE = aMgr.GetImageThrow("IMAGE_VERTCREASE");
		IMAGE_WADSWORTH = aMgr.GetImageThrow("IMAGE_WADSWORTH");
		IMAGE_WAIT_BAR = aMgr.GetImageThrow("IMAGE_WAIT_BAR");
		IMAGE_WALTER = aMgr.GetImageThrow("IMAGE_WALTER");
		IMAGE_WARPGLOW = aMgr.GetImageThrow("IMAGE_WARPGLOW");
		IMAGE_WARPHOLE = aMgr.GetImageThrow("IMAGE_WARPHOLE");
		IMAGE_WAVE = aMgr.GetImageThrow("IMAGE_WAVE");
		IMAGE_WAVESIDE = aMgr.GetImageThrow("IMAGE_WAVESIDE");
		IMAGE_WELCOMEBACK = aMgr.GetImageThrow("IMAGE_WELCOMEBACK");
		IMAGE_WELCOMETO = aMgr.GetImageThrow("IMAGE_WELCOMETO");
		IMAGE_ZORF = aMgr.GetImageThrow("IMAGE_ZORF");
		IMAGE_ZZZ = aMgr.GetImageThrow("IMAGE_ZZZ");
		SOUND_APPLAUSE = aMgr.GetSoundThrow("SOUND_APPLAUSE");
		SOUND_AWOOGA = aMgr.GetSoundThrow("SOUND_AWOOGA");
		SOUND_BABY = aMgr.GetSoundThrow("SOUND_BABY");
		SOUND_BONUSCOLLECT = aMgr.GetSoundThrow("SOUND_BONUSCOLLECT");
		SOUND_BONUSCOUNT = aMgr.GetSoundThrow("SOUND_BONUSCOUNT");
		SOUND_BUBBLES = aMgr.GetSoundThrow("SOUND_BUBBLES");
		SOUND_BUY = aMgr.GetSoundThrow("SOUND_BUY");
		SOUND_BUZZER = aMgr.GetSoundThrow("SOUND_BUZZER");
		SOUND_CHOMP = aMgr.GetSoundThrow("SOUND_CHOMP");
		SOUND_CHOMP2 = aMgr.GetSoundThrow("SOUND_CHOMP2");
		SOUND_CROWNED = aMgr.GetSoundThrow("SOUND_CROWNED");
		SOUND_DIAMOND = aMgr.GetSoundThrow("SOUND_DIAMOND");
		SOUND_DIE = aMgr.GetSoundThrow("SOUND_DIE");
		SOUND_DROPFOOD = aMgr.GetSoundThrow("SOUND_DROPFOOD");
		SOUND_EEL1 = aMgr.GetSoundThrow("SOUND_EEL1");
		SOUND_EEL2 = aMgr.GetSoundThrow("SOUND_EEL2");
		SOUND_EEL3 = aMgr.GetSoundThrow("SOUND_EEL3");
		SOUND_EVILLAFF = aMgr.GetSoundThrow("SOUND_EVILLAFF");
		SOUND_EXPLODE = aMgr.GetSoundThrow("SOUND_EXPLODE");
		SOUND_EXPLOSION1 = aMgr.GetSoundThrow("SOUND_EXPLOSION1");
		SOUND_EXPLOSION4 = aMgr.GetSoundThrow("SOUND_EXPLOSION4");
		SOUND_FART = aMgr.GetSoundThrow("SOUND_FART");
		SOUND_FART2 = aMgr.GetSoundThrow("SOUND_FART2");
		SOUND_GROW = aMgr.GetSoundThrow("SOUND_GROW");
		SOUND_GUFFAW = aMgr.GetSoundThrow("SOUND_GUFFAW");
		SOUND_HATCH = aMgr.GetSoundThrow("SOUND_HATCH");
		SOUND_HEAL = aMgr.GetSoundThrow("SOUND_HEAL");
		SOUND_HIT = aMgr.GetSoundThrow("SOUND_HIT");
		SOUND_INTERFER = aMgr.GetSoundThrow("SOUND_INTERFER");
		SOUND_MISSLE = aMgr.GetSoundThrow("SOUND_MISSLE");
		SOUND_NIKOCLOSE = aMgr.GetSoundThrow("SOUND_NIKOCLOSE");
		SOUND_NIKOOPEN = aMgr.GetSoundThrow("SOUND_NIKOOPEN");
		SOUND_PEARL = aMgr.GetSoundThrow("SOUND_PEARL");
		SOUND_POINTS = aMgr.GetSoundThrow("SOUND_POINTS");
		SOUND_POINTS2 = aMgr.GetSoundThrow("SOUND_POINTS2");
		SOUND_POINTS3 = aMgr.GetSoundThrow("SOUND_POINTS3");
		SOUND_POINTS4 = aMgr.GetSoundThrow("SOUND_POINTS4");
		SOUND_PRIMALSCREAM = aMgr.GetSoundThrow("SOUND_PRIMALSCREAM");
		SOUND_PUNCH = aMgr.GetSoundThrow("SOUND_PUNCH");
		SOUND_RATTLE = aMgr.GetSoundThrow("SOUND_RATTLE");
		SOUND_RICOCHET = aMgr.GetSoundThrow("SOUND_RICOCHET");
		SOUND_ROAR = aMgr.GetSoundThrow("SOUND_ROAR");
		SOUND_ROAR2 = aMgr.GetSoundThrow("SOUND_ROAR2");
		SOUND_ROAR3 = aMgr.GetSoundThrow("SOUND_ROAR3");
		SOUND_SFX = aMgr.GetSoundThrow("SOUND_SFX");
		SOUND_SING = aMgr.GetSoundThrow("SOUND_SING");
		SOUND_SLURP = aMgr.GetSoundThrow("SOUND_SLURP");
		SOUND_SLURP2 = aMgr.GetSoundThrow("SOUND_SLURP2");
		SOUND_SLURP3 = aMgr.GetSoundThrow("SOUND_SLURP3");
		SOUND_SNEEZE = aMgr.GetSoundThrow("SOUND_SNEEZE");
		SOUND_SONAR = aMgr.GetSoundThrow("SOUND_SONAR");
		SOUND_SPLASH = aMgr.GetSoundThrow("SOUND_SPLASH");
		SOUND_SPLASH2 = aMgr.GetSoundThrow("SOUND_SPLASH2");
		SOUND_SPLASH3 = aMgr.GetSoundThrow("SOUND_SPLASH3");
		SOUND_SPLASHBIG = aMgr.GetSoundThrow("SOUND_SPLASHBIG");
		SOUND_TAPGLASS = aMgr.GetSoundThrow("SOUND_TAPGLASS");
		SOUND_TONE = aMgr.GetSoundThrow("SOUND_TONE");
		SOUND_TONEHI = aMgr.GetSoundThrow("SOUND_TONEHI");
		SOUND_TONELO = aMgr.GetSoundThrow("SOUND_TONELO");
		SOUND_TONESUPERHI = aMgr.GetSoundThrow("SOUND_TONESUPERHI");
		SOUND_TREASURE = aMgr.GetSoundThrow("SOUND_TREASURE");
		SOUND_UNLEASH = aMgr.GetSoundThrow("SOUND_UNLEASH");
		SOUND_ZAP = aMgr.GetSoundThrow("SOUND_ZAP");
		SOUND_ZZAM = aMgr.GetSoundThrow("SOUND_ZZAM");
	}
	catch (ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Register Resources
Font* Sexy::FONT_BLAMBOTPRO15;
Font* Sexy::FONT_BLAMBOTPRO8;
Font* Sexy::FONT_CONTINUUMBOLD12;
Font* Sexy::FONT_CONTINUUMBOLD12OUTLINE;
Font* Sexy::FONT_CONTINUUMBOLD14;
Font* Sexy::FONT_CONTINUUMBOLD14OUTLINE;
Font* Sexy::FONT_JUNGLEFEVER12OUTLINE;
Font* Sexy::FONT_JUNGLEFEVER15OUTLINE;
Font* Sexy::FONT_LIDDIE12;
Font* Sexy::FONT_LIDDIE15;
Font* Sexy::FONT_LIDDIE18;
Font* Sexy::FONT_TINY;
Font* Sexy::FONT_TINYBOLD;
Image* Sexy::IMAGE_DIALOG;
Image* Sexy::IMAGE_DIALOGBUTTON;
Image* Sexy::IMAGE_EDITBOX;

bool Sexy::ExtractRegisterResources(ResourceManager* theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager& aMgr = *theManager;
	try
	{
		FONT_BLAMBOTPRO15 = aMgr.GetFontThrow("FONT_BLAMBOTPRO15");
		FONT_BLAMBOTPRO8 = aMgr.GetFontThrow("FONT_BLAMBOTPRO8");
		FONT_CONTINUUMBOLD12 = aMgr.GetFontThrow("FONT_CONTINUUMBOLD12");
		FONT_CONTINUUMBOLD12OUTLINE = aMgr.GetFontThrow("FONT_CONTINUUMBOLD12OUTLINE");
		FONT_CONTINUUMBOLD14 = aMgr.GetFontThrow("FONT_CONTINUUMBOLD14");
		FONT_CONTINUUMBOLD14OUTLINE = aMgr.GetFontThrow("FONT_CONTINUUMBOLD14OUTLINE");
		FONT_JUNGLEFEVER12OUTLINE = aMgr.GetFontThrow("FONT_JUNGLEFEVER12OUTLINE");
		FONT_JUNGLEFEVER15OUTLINE = aMgr.GetFontThrow("FONT_JUNGLEFEVER15OUTLINE");
		FONT_LIDDIE12 = aMgr.GetFontThrow("FONT_LIDDIE12");
		FONT_LIDDIE15 = aMgr.GetFontThrow("FONT_LIDDIE15");
		FONT_LIDDIE18 = aMgr.GetFontThrow("FONT_LIDDIE18");
		FONT_TINY = aMgr.GetFontThrow("FONT_TINY");
		FONT_TINYBOLD = aMgr.GetFontThrow("FONT_TINYBOLD");
		IMAGE_DIALOG = aMgr.GetImageThrow("IMAGE_DIALOG");
		IMAGE_DIALOGBUTTON = aMgr.GetImageThrow("IMAGE_DIALOGBUTTON");
		IMAGE_EDITBOX = aMgr.GetImageThrow("IMAGE_EDITBOX");
	}
	catch (ResourceManagerException&)
	{
		return false;
	}
	return true;
}

static void* gResources[] =
{
	&IMAGE_CURSOR_POINTER,
	&IMAGE_CURSOR_HAND,
	&IMAGE_CURSOR_DRAGGING,
	&IMAGE_CURSOR_TEXT,
	&IMAGE_BLANK,
	&IMAGE_TITLEPAGE,
	&IMAGE_TITLEPAGEMASK,
	&IMAGE_LOADERBAR,
	&IMAGE_LOADERBAROVER,
	&IMAGE_LOADERBARLOADING,
	&IMAGE_LOADERPLAY,
	&FONT_JUNGLEFEVER10OUTLINE,
	&FONT_JUNGLEFEVER17OUTLINE,
	&SOUND_BUTTONCLICK,
	&FONT_LIDDIE12,
	&FONT_LIDDIE15,
	&FONT_LIDDIE18,
	&FONT_JUNGLEFEVER12OUTLINE,
	&FONT_JUNGLEFEVER15OUTLINE,
	&FONT_BLAMBOTPRO8,
	&FONT_BLAMBOTPRO15,
	&FONT_TINY,
	&FONT_TINYBOLD,
	&FONT_CONTINUUMBOLD12,
	&FONT_CONTINUUMBOLD12OUTLINE,
	&FONT_CONTINUUMBOLD14,
	&FONT_CONTINUUMBOLD14OUTLINE,
	&IMAGE_DIALOG,
	&IMAGE_DIALOGBUTTON,
	&IMAGE_EDITBOX,
	&IMAGE_SELECTORSCREEN,
	&IMAGE_STORESCREEN,
	&IMAGE_HATCHSCREEN,
	&IMAGE_MAINBUTTON,
	&IMAGE_LEFTBUTTON,
	&IMAGE_RIGHTBUTTON,
	&IMAGE_CENTERBUTTON,
	&IMAGE_SCREENBACK,
	&IMAGE_SCREENTITLE,
	&IMAGE_SCREENTITLEHOLE,
	&IMAGE_FISHBOX,
	&IMAGE_FISHBOXBUTTON,
	&IMAGE_PETBUTTON,
	&IMAGE_PETBUTTONRING,
	&IMAGE_PETBUTTONREFLECT,
	&IMAGE_PETBUTTONHOLE,
	&IMAGE_STORELEFTBUTTON,
	&IMAGE_STORETOPBUTTON,
	&IMAGE_STORERIGHTBUTTON,
	&IMAGE_STORELEFTHILIGHT,
	&IMAGE_STORETOPHILIGHT,
	&IMAGE_STORERIGHTHILIGHT,
	&IMAGE_BATTLETANKBUTTON,
	&IMAGE_BATTLETANKBUTTOND,
	&IMAGE_MIDDLEBUTTON,
	&IMAGE_MIDDLEBUTTOND,
	&IMAGE_OPTIONSBUTTON,
	&IMAGE_OPTIONSBUTTOND,
	&IMAGE_MENUBTND,
	&IMAGE_MENUBTND2,
	&IMAGE_MENUBTNU,
	&IMAGE_MENUBTNO,
	&IMAGE_PETBTNU,
	&IMAGE_PETBTNO,
	&IMAGE_UNCHECKED,
	&IMAGE_CHECKED,
	&IMAGE_SLIDERTRACK,
	&IMAGE_SLIDERTHUMB,
	&IMAGE_WAIT_BAR,
	&IMAGE_MENUBAR,
	&IMAGE_MONEYFLASH,
	&IMAGE_MENUBUTTONREFLECTION,
	&IMAGE_TROPHYBAR,
	&IMAGE_SPEECHBUBBLE,
	&IMAGE_SHADOW,
	&IMAGE_HATCHREFLECTION,
	&IMAGE_SELECTORSPEECHBUBBLE,
	&IMAGE_HELPARROW,
	&IMAGE_TANKCHOOSER,
	&IMAGE_BOLT,
	&IMAGE_HORZCREASE,
	&IMAGE_VERTCREASE,
	&IMAGE_BUBBULATOR_STORE,
	&IMAGE_AA_STORE,
	&IMAGE_ZZZ,
	&IMAGE_BONUSBUCKET,
	&IMAGE_HELPALIEN,
	&IMAGE_HELPPETCHOOSE,
	&IMAGE_HELPSCREENSAVER,
	&IMAGE_BONUS1,
	&IMAGE_BONUS2,
	&IMAGE_BONUS3,
	&IMAGE_WELCOMETO,
	&IMAGE_WELCOMEBACK,
	&IMAGE_PIZZA,
	&IMAGE_ICECREAM,
	&IMAGE_CHICKEN,
	&IMAGE_SPARKLE,
	&IMAGE_TANKBACKDROP1,
	&IMAGE_TANKBACKDROP2,
	&IMAGE_TANKBACKDROP3,
	&IMAGE_TANKBACKDROP4,
	&IMAGE_TANKBACKDROP5,
	&IMAGE_TANKBACKDROP6,
	&IMAGE_HEALTHBAR,
	&IMAGE_HEALTHBARTUBE,
	&IMAGE_HELPSHELL,
	&IMAGE_STORESHELL,
	&IMAGE_BONUSBUTTONOVERLAY,
	&IMAGE_FATBUTTON,
	&IMAGE_EGGBRINKLEY,
	&IMAGE_EGGNOSTRADAMUS,
	&IMAGE_EGGSTANLEY,
	&IMAGE_EGGWALTER,
	&IMAGE_PETLIMITEGG,
	&IMAGE_BONUSAWARD,
	&IMAGE_BONUSAWARD2,
	&IMAGE_AA_BEAM,
	&IMAGE_AA_GLOW,
	&IMAGE_AA_TOP1,
	&IMAGE_AA_TOP2,
	&IMAGE_AA_BOTTOM,
	&IMAGE_SPARKS,
	&IMAGE_ENERGYBALL,
	&IMAGE_CHOMP,
	&IMAGE_LASERS,
	&IMAGE_BUBBLES,
	&IMAGE_MONEY,
	&IMAGE_PEARL,
	&IMAGE_PEANUT,
	&IMAGE_MISCITEMS,
	&IMAGE_SHELLS,
	&IMAGE_MONEYBAG,
	&IMAGE_FOOD,
	&IMAGE_BALLS,
	&IMAGE_MERYLLIPS,
	&IMAGE_MERYLBLINK,
	&IMAGE_MERYLTAIL,
	&IMAGE_CROSSHAIR,
	&IMAGE_HATCHANIMATION,
	&IMAGE_TROPHYBUTTONS,
	&IMAGE_EXPLOSION,
	&IMAGE_EXPLOSIONSMALL,
	&IMAGE_EXPLOSIONTINY,
	&IMAGE_SMOKETINY,
	&IMAGE_SMOKESMALL,
	&IMAGE_SMOKEMISSILE,
	&IMAGE_WARPHOLE,
	&IMAGE_WARPGLOW,
	&IMAGE_EGGPIECES,
	&IMAGE_EGGSHARDS,
	&IMAGE_EGGCRACK1,
	&IMAGE_EGGCRACK2,
	&IMAGE_BUBBULATOR,
	&IMAGE_STOREBACKDROPS,
	&IMAGE_WAVESIDE,
	&IMAGE_WAVE,
	&IMAGE_LASERUPGRADES,
	&IMAGE_MISSILE,
	&IMAGE_AQUARIUM1,
	&IMAGE_AQUARIUM2,
	&IMAGE_AQUARIUM3,
	&IMAGE_AQUARIUM4,
	&IMAGE_AQUARIUM5,
	&IMAGE_AQUARIUM6,
	&IMAGE_TANKMASK1,
	&IMAGE_TANKMASK2,
	&IMAGE_TANKMASK3,
	&IMAGE_TANKMASK4,
	&IMAGE_TANKMASK5,
	&IMAGE_TANKMASK6,
	&IMAGE_SMALLTURN,
	&IMAGE_HUNGRYTURN,
	&IMAGE_HUNGRYEAT,
	&IMAGE_SIMTURN1,
	&IMAGE_SIMTURN2,
	&IMAGE_SIMTURN3,
	&IMAGE_SMALLEAT,
	&IMAGE_SMALLDIE,
	&IMAGE_HUNGRYSWIM,
	&IMAGE_HUNGRYBREEDER,
	&IMAGE_SIMEAT1,
	&IMAGE_SIMEAT2,
	&IMAGE_SIMEAT3,
	&IMAGE_SIMSWIM1,
	&IMAGE_SIMSWIM2,
	&IMAGE_SIMSWIM3,
	&IMAGE_SIMCARNIVORE,
	&IMAGE_TANKLIGHTING,
	&IMAGE_SYLV,
	&IMAGE_BALROG,
	&IMAGE_GUS,
	&IMAGE_DESTRUCTOR,
	&IMAGE_ULYSSES,
	&IMAGE_PSYCHOSQUID,
	&IMAGE_BILATERUS,
	&IMAGE_MINISYLV,
	&IMAGE_BOSS,
	&IMAGE_HALO,
	&IMAGE_GUMBOLIGHT,
	&IMAGE_AMPCHARGE,
	&IMAGE_NIKOTOWER,
	&IMAGE_STINKY,
	&IMAGE_NIKO,
	&IMAGE_ITCHY,
	&IMAGE_PREGO,
	&IMAGE_ZORF,
	&IMAGE_CLYDE,
	&IMAGE_VERT,
	&IMAGE_RUFUS,
	&IMAGE_MERYL,
	&IMAGE_WADSWORTH,
	&IMAGE_SEYMOUR,
	&IMAGE_SHRAPNEL,
	&IMAGE_GUMBO,
	&IMAGE_BLIP,
	&IMAGE_RHUBARB,
	&IMAGE_NIMBUS,
	&IMAGE_AMP,
	&IMAGE_GASH,
	&IMAGE_ANGIE,
	&IMAGE_PRESTO,
	&IMAGE_BRINKLEY,
	&IMAGE_NOSTRADAMUS,
	&IMAGE_STANLEY,
	&IMAGE_WALTER,
	&IMAGE_SMALLSWIM,
	&IMAGE_GRUBBER,
	&IMAGE_STARCATCHER,
	&IMAGE_GEKKO,
	&IMAGE_BREEDER,
	&IMAGE_ULTRA,
	&IMAGE_SCL_STINKY,
	&IMAGE_SCL_NIKO,
	&IMAGE_SCL_ITCHY,
	&IMAGE_SCL_PREGO,
	&IMAGE_SCL_ZORF,
	&IMAGE_SCL_CLYDE,
	&IMAGE_SCL_VERT,
	&IMAGE_SCL_RUFUS,
	&IMAGE_SCL_MERYL,
	&IMAGE_SCL_WADSWORTH,
	&IMAGE_SCL_SEYMOUR,
	&IMAGE_SCL_SHRAPNEL,
	&IMAGE_SCL_GUMBO,
	&IMAGE_SCL_BLIP,
	&IMAGE_SCL_RHUBARB,
	&IMAGE_SCL_NIMBUS,
	&IMAGE_SCL_AMP,
	&IMAGE_SCL_GASH,
	&IMAGE_SCL_ANGIE,
	&IMAGE_SCL_PRESTO,
	&IMAGE_SCL_BRINKLEY,
	&IMAGE_SCL_NOSTRADAMUS,
	&IMAGE_SCL_STANLEY,
	&IMAGE_SCL_WALTER,
	&IMAGE_SCL_OSCAR,
	&IMAGE_SCL_GRUBBER,
	&IMAGE_SCL_STARCATCHER,
	&IMAGE_SCL_GEKKO,
	&IMAGE_SCL_BREEDER,
	&IMAGE_SCL_ULTRA,
	&SOUND_AWOOGA,
	&SOUND_APPLAUSE,
	&SOUND_BABY,
	&SOUND_BONUSCOUNT,
	&SOUND_TONE,
	&SOUND_TONELO,
	&SOUND_TONEHI,
	&SOUND_TONESUPERHI,
	&SOUND_PRIMALSCREAM,
	&SOUND_BONUSCOLLECT,
	&SOUND_BUBBLES,
	&SOUND_BUY,
	&SOUND_BUZZER,
	&SOUND_CHOMP,
	&SOUND_CHOMP2,
	&SOUND_CROWNED,
	&SOUND_DIAMOND,
	&SOUND_DIE,
	&SOUND_DROPFOOD,
	&SOUND_EEL1,
	&SOUND_EEL2,
	&SOUND_EEL3,
	&SOUND_EVILLAFF,
	&SOUND_EXPLODE,
	&SOUND_EXPLOSION1,
	&SOUND_EXPLOSION4,
	&SOUND_FART,
	&SOUND_FART2,
	&SOUND_GROW,
	&SOUND_GUFFAW,
	&SOUND_HATCH,
	&SOUND_HEAL,
	&SOUND_HIT,
	&SOUND_INTERFER,
	&SOUND_MISSLE,
	&SOUND_NIKOOPEN,
	&SOUND_NIKOCLOSE,
	&SOUND_PEARL,
	&SOUND_POINTS,
	&SOUND_POINTS2,
	&SOUND_POINTS3,
	&SOUND_POINTS4,
	&SOUND_PUNCH,
	&SOUND_RATTLE,
	&SOUND_RICOCHET,
	&SOUND_ROAR,
	&SOUND_ROAR2,
	&SOUND_ROAR3,
	&SOUND_SFX,
	&SOUND_SING,
	&SOUND_SLURP,
	&SOUND_SLURP2,
	&SOUND_SLURP3,
	&SOUND_SNEEZE,
	&SOUND_SONAR,
	&SOUND_SPLASH,
	&SOUND_SPLASH2,
	&SOUND_SPLASH3,
	&SOUND_SPLASHBIG,
	&SOUND_TAPGLASS,
	&SOUND_TREASURE,
	&SOUND_UNLEASH,
	&SOUND_ZAP,
	&SOUND_ZZAM,
	NULL
};

Image* Sexy::LoadImageById(ResourceManager* theManager, int theId)
{
	return (*((Image**)gResources[theId]) = theManager->LoadImage(GetStringIdById(theId)));
}

void Sexy::ReplaceImageById(ResourceManager* theManager, int theId, Image* theImage)
{
	theManager->ReplaceImage(GetStringIdById(theId), theImage);
	*(Image**)gResources[theId] = theImage;
}

Image* Sexy::GetImageById(int theId)
{
	return *(Image**)gResources[theId];
}

Font* Sexy::GetFontById(int theId)
{
	return *(Font**)gResources[theId];
}

int Sexy::GetSoundById(int theId)
{
	return *(int*)gResources[theId];
}

Image*& Sexy::GetImageRefById(int theId)
{
	return *(Image**)gResources[theId];
}

Font*& Sexy::GetFontRefById(int theId)
{
	return *(Font**)gResources[theId];
}

int& Sexy::GetSoundRefById(int theId)
{
	return *(int*)gResources[theId];
}

static Sexy::ResourceId GetIdByVariable(const void* theVariable)
{
	typedef std::map<intptr_t, int> MyMap;
	static MyMap aMap;
	if (gNeedRecalcVariableToIdMap)
	{
		gNeedRecalcVariableToIdMap = false;
		aMap.clear();
		for (int i = 0; i < RESOURCE_ID_MAX; i++)
			aMap[*(intptr_t *)gResources[i]] = i;
	}

	MyMap::iterator anItr = aMap.find((intptr_t)theVariable);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId)anItr->second;
}

Sexy::ResourceId Sexy::GetIdByImage(Image* theImage)
{
	return GetIdByVariable(theImage);
}

Sexy::ResourceId Sexy::GetIdByFont(Font* theFont)
{
	return GetIdByVariable(theFont);
}

Sexy::ResourceId Sexy::GetIdBySound(int theSound)
{
	return GetIdByVariable((void*)(intptr_t)theSound);
}

const char* Sexy::GetStringIdById(int theId)
{
	switch (theId)
	{
	case IMAGE_CURSOR_POINTER_ID: return "IMAGE_CURSOR_POINTER";
	case IMAGE_CURSOR_HAND_ID: return "IMAGE_CURSOR_HAND";
	case IMAGE_CURSOR_DRAGGING_ID: return "IMAGE_CURSOR_DRAGGING";
	case IMAGE_CURSOR_TEXT_ID: return "IMAGE_CURSOR_TEXT";
	case IMAGE_BLANK_ID: return "IMAGE_BLANK";
	case IMAGE_TITLEPAGE_ID: return "IMAGE_TITLEPAGE";
	case IMAGE_TITLEPAGEMASK_ID: return "IMAGE_TITLEPAGEMASK";
	case IMAGE_LOADERBAR_ID: return "IMAGE_LOADERBAR";
	case IMAGE_LOADERBAROVER_ID: return "IMAGE_LOADERBAROVER";
	case IMAGE_LOADERBARLOADING_ID: return "IMAGE_LOADERBARLOADING";
	case IMAGE_LOADERPLAY_ID: return "IMAGE_LOADERPLAY";
	case FONT_JUNGLEFEVER10OUTLINE_ID: return "FONT_JUNGLEFEVER10OUTLINE";
	case FONT_JUNGLEFEVER17OUTLINE_ID: return "FONT_JUNGLEFEVER17OUTLINE";
	case SOUND_BUTTONCLICK_ID: return "SOUND_BUTTONCLICK";
	case FONT_LIDDIE12_ID: return "FONT_LIDDIE12";
	case FONT_LIDDIE15_ID: return "FONT_LIDDIE15";
	case FONT_LIDDIE18_ID: return "FONT_LIDDIE18";
	case FONT_JUNGLEFEVER12OUTLINE_ID: return "FONT_JUNGLEFEVER12OUTLINE";
	case FONT_JUNGLEFEVER15OUTLINE_ID: return "FONT_JUNGLEFEVER15OUTLINE";
	case FONT_BLAMBOTPRO8_ID: return "FONT_BLAMBOTPRO8";
	case FONT_BLAMBOTPRO15_ID: return "FONT_BLAMBOTPRO15";
	case FONT_TINY_ID: return "FONT_TINY";
	case FONT_TINYBOLD_ID: return "FONT_TINYBOLD";
	case FONT_CONTINUUMBOLD12_ID: return "FONT_CONTINUUMBOLD12";
	case FONT_CONTINUUMBOLD12OUTLINE_ID: return "FONT_CONTINUUMBOLD12OUTLINE";
	case FONT_CONTINUUMBOLD14_ID: return "FONT_CONTINUUMBOLD14";
	case FONT_CONTINUUMBOLD14OUTLINE_ID: return "FONT_CONTINUUMBOLD14OUTLINE";
	case IMAGE_DIALOG_ID: return "IMAGE_DIALOG";
	case IMAGE_DIALOGBUTTON_ID: return "IMAGE_DIALOGBUTTON";
	case IMAGE_EDITBOX_ID: return "IMAGE_EDITBOX";
	case IMAGE_SELECTORSCREEN_ID: return "IMAGE_SELECTORSCREEN";
	case IMAGE_STORESCREEN_ID: return "IMAGE_STORESCREEN";
	case IMAGE_HATCHSCREEN_ID: return "IMAGE_HATCHSCREEN";
	case IMAGE_MAINBUTTON_ID: return "IMAGE_MAINBUTTON";
	case IMAGE_LEFTBUTTON_ID: return "IMAGE_LEFTBUTTON";
	case IMAGE_RIGHTBUTTON_ID: return "IMAGE_RIGHTBUTTON";
	case IMAGE_CENTERBUTTON_ID: return "IMAGE_CENTERBUTTON";
	case IMAGE_SCREENBACK_ID: return "IMAGE_SCREENBACK";
	case IMAGE_SCREENTITLE_ID: return "IMAGE_SCREENTITLE";
	case IMAGE_SCREENTITLEHOLE_ID: return "IMAGE_SCREENTITLEHOLE";
	case IMAGE_FISHBOX_ID: return "IMAGE_FISHBOX";
	case IMAGE_FISHBOXBUTTON_ID: return "IMAGE_FISHBOXBUTTON";
	case IMAGE_PETBUTTON_ID: return "IMAGE_PETBUTTON";
	case IMAGE_PETBUTTONRING_ID: return "IMAGE_PETBUTTONRING";
	case IMAGE_PETBUTTONREFLECT_ID: return "IMAGE_PETBUTTONREFLECT";
	case IMAGE_PETBUTTONHOLE_ID: return "IMAGE_PETBUTTONHOLE";
	case IMAGE_STORELEFTBUTTON_ID: return "IMAGE_STORELEFTBUTTON";
	case IMAGE_STORETOPBUTTON_ID: return "IMAGE_STORETOPBUTTON";
	case IMAGE_STORERIGHTBUTTON_ID: return "IMAGE_STORERIGHTBUTTON";
	case IMAGE_STORELEFTHILIGHT_ID: return "IMAGE_STORELEFTHILIGHT";
	case IMAGE_STORETOPHILIGHT_ID: return "IMAGE_STORETOPHILIGHT";
	case IMAGE_STORERIGHTHILIGHT_ID: return "IMAGE_STORERIGHTHILIGHT";
	case IMAGE_BATTLETANKBUTTON_ID: return "IMAGE_BATTLETANKBUTTON";
	case IMAGE_BATTLETANKBUTTOND_ID: return "IMAGE_BATTLETANKBUTTOND";
	case IMAGE_MIDDLEBUTTON_ID: return "IMAGE_MIDDLEBUTTON";
	case IMAGE_MIDDLEBUTTOND_ID: return "IMAGE_MIDDLEBUTTOND";
	case IMAGE_OPTIONSBUTTON_ID: return "IMAGE_OPTIONSBUTTON";
	case IMAGE_OPTIONSBUTTOND_ID: return "IMAGE_OPTIONSBUTTOND";
	case IMAGE_MENUBTND_ID: return "IMAGE_MENUBTND";
	case IMAGE_MENUBTND2_ID: return "IMAGE_MENUBTND2";
	case IMAGE_MENUBTNU_ID: return "IMAGE_MENUBTNU";
	case IMAGE_MENUBTNO_ID: return "IMAGE_MENUBTNO";
	case IMAGE_PETBTNU_ID: return "IMAGE_PETBTNU";
	case IMAGE_PETBTNO_ID: return "IMAGE_PETBTNO";
	case IMAGE_UNCHECKED_ID: return "IMAGE_UNCHECKED";
	case IMAGE_CHECKED_ID: return "IMAGE_CHECKED";
	case IMAGE_SLIDERTRACK_ID: return "IMAGE_SLIDERTRACK";
	case IMAGE_SLIDERTHUMB_ID: return "IMAGE_SLIDERTHUMB";
	case IMAGE_WAIT_BAR_ID: return "IMAGE_WAIT_BAR";
	case IMAGE_MENUBAR_ID: return "IMAGE_MENUBAR";
	case IMAGE_MONEYFLASH_ID: return "IMAGE_MONEYFLASH";
	case IMAGE_MENUBUTTONREFLECTION_ID: return "IMAGE_MENUBUTTONREFLECTION";
	case IMAGE_TROPHYBAR_ID: return "IMAGE_TROPHYBAR";
	case IMAGE_SPEECHBUBBLE_ID: return "IMAGE_SPEECHBUBBLE";
	case IMAGE_SHADOW_ID: return "IMAGE_SHADOW";
	case IMAGE_HATCHREFLECTION_ID: return "IMAGE_HATCHREFLECTION";
	case IMAGE_SELECTORSPEECHBUBBLE_ID: return "IMAGE_SELECTORSPEECHBUBBLE";
	case IMAGE_HELPARROW_ID: return "IMAGE_HELPARROW";
	case IMAGE_TANKCHOOSER_ID: return "IMAGE_TANKCHOOSER";
	case IMAGE_BOLT_ID: return "IMAGE_BOLT";
	case IMAGE_HORZCREASE_ID: return "IMAGE_HORZCREASE";
	case IMAGE_VERTCREASE_ID: return "IMAGE_VERTCREASE";
	case IMAGE_BUBBULATOR_STORE_ID: return "IMAGE_BUBBULATOR_STORE";
	case IMAGE_AA_STORE_ID: return "IMAGE_AA_STORE";
	case IMAGE_ZZZ_ID: return "IMAGE_ZZZ";
	case IMAGE_BONUSBUCKET_ID: return "IMAGE_BONUSBUCKET";
	case IMAGE_HELPALIEN_ID: return "IMAGE_HELPALIEN";
	case IMAGE_HELPPETCHOOSE_ID: return "IMAGE_HELPPETCHOOSE";
	case IMAGE_HELPSCREENSAVER_ID: return "IMAGE_HELPSCREENSAVER";
	case IMAGE_BONUS1_ID: return "IMAGE_BONUS1";
	case IMAGE_BONUS2_ID: return "IMAGE_BONUS2";
	case IMAGE_BONUS3_ID: return "IMAGE_BONUS3";
	case IMAGE_WELCOMETO_ID: return "IMAGE_WELCOMETO";
	case IMAGE_WELCOMEBACK_ID: return "IMAGE_WELCOMEBACK";
	case IMAGE_PIZZA_ID: return "IMAGE_PIZZA";
	case IMAGE_ICECREAM_ID: return "IMAGE_ICECREAM";
	case IMAGE_CHICKEN_ID: return "IMAGE_CHICKEN";
	case IMAGE_SPARKLE_ID: return "IMAGE_SPARKLE";
	case IMAGE_TANKBACKDROP1_ID: return "IMAGE_TANKBACKDROP1";
	case IMAGE_TANKBACKDROP2_ID: return "IMAGE_TANKBACKDROP2";
	case IMAGE_TANKBACKDROP3_ID: return "IMAGE_TANKBACKDROP3";
	case IMAGE_TANKBACKDROP4_ID: return "IMAGE_TANKBACKDROP4";
	case IMAGE_TANKBACKDROP5_ID: return "IMAGE_TANKBACKDROP5";
	case IMAGE_TANKBACKDROP6_ID: return "IMAGE_TANKBACKDROP6";
	case IMAGE_HEALTHBAR_ID: return "IMAGE_HEALTHBAR";
	case IMAGE_HEALTHBARTUBE_ID: return "IMAGE_HEALTHBARTUBE";
	case IMAGE_HELPSHELL_ID: return "IMAGE_HELPSHELL";
	case IMAGE_STORESHELL_ID: return "IMAGE_STORESHELL";
	case IMAGE_BONUSBUTTONOVERLAY_ID: return "IMAGE_BONUSBUTTONOVERLAY";
	case IMAGE_FATBUTTON_ID: return "IMAGE_FATBUTTON";
	case IMAGE_EGGBRINKLEY_ID: return "IMAGE_EGGBRINKLEY";
	case IMAGE_EGGNOSTRADAMUS_ID: return "IMAGE_EGGNOSTRADAMUS";
	case IMAGE_EGGSTANLEY_ID: return "IMAGE_EGGSTANLEY";
	case IMAGE_EGGWALTER_ID: return "IMAGE_EGGWALTER";
	case IMAGE_PETLIMITEGG_ID: return "IMAGE_PETLIMITEGG";
	case IMAGE_BONUSAWARD_ID: return "IMAGE_BONUSAWARD";
	case IMAGE_BONUSAWARD2_ID: return "IMAGE_BONUSAWARD2";
	case IMAGE_AA_BEAM_ID: return "IMAGE_AA_BEAM";
	case IMAGE_AA_GLOW_ID: return "IMAGE_AA_GLOW";
	case IMAGE_AA_TOP1_ID: return "IMAGE_AA_TOP1";
	case IMAGE_AA_TOP2_ID: return "IMAGE_AA_TOP2";
	case IMAGE_AA_BOTTOM_ID: return "IMAGE_AA_BOTTOM";
	case IMAGE_SPARKS_ID: return "IMAGE_SPARKS";
	case IMAGE_ENERGYBALL_ID: return "IMAGE_ENERGYBALL";
	case IMAGE_CHOMP_ID: return "IMAGE_CHOMP";
	case IMAGE_LASERS_ID: return "IMAGE_LASERS";
	case IMAGE_BUBBLES_ID: return "IMAGE_BUBBLES";
	case IMAGE_MONEY_ID: return "IMAGE_MONEY";
	case IMAGE_PEARL_ID: return "IMAGE_PEARL";
	case IMAGE_PEANUT_ID: return "IMAGE_PEANUT";
	case IMAGE_MISCITEMS_ID: return "IMAGE_MISCITEMS";
	case IMAGE_SHELLS_ID: return "IMAGE_SHELLS";
	case IMAGE_MONEYBAG_ID: return "IMAGE_MONEYBAG";
	case IMAGE_FOOD_ID: return "IMAGE_FOOD";
	case IMAGE_BALLS_ID: return "IMAGE_BALLS";
	case IMAGE_MERYLLIPS_ID: return "IMAGE_MERYLLIPS";
	case IMAGE_MERYLBLINK_ID: return "IMAGE_MERYLBLINK";
	case IMAGE_MERYLTAIL_ID: return "IMAGE_MERYLTAIL";
	case IMAGE_CROSSHAIR_ID: return "IMAGE_CROSSHAIR";
	case IMAGE_HATCHANIMATION_ID: return "IMAGE_HATCHANIMATION";
	case IMAGE_TROPHYBUTTONS_ID: return "IMAGE_TROPHYBUTTONS";
	case IMAGE_EXPLOSION_ID: return "IMAGE_EXPLOSION";
	case IMAGE_EXPLOSIONSMALL_ID: return "IMAGE_EXPLOSIONSMALL";
	case IMAGE_EXPLOSIONTINY_ID: return "IMAGE_EXPLOSIONTINY";
	case IMAGE_SMOKETINY_ID: return "IMAGE_SMOKETINY";
	case IMAGE_SMOKESMALL_ID: return "IMAGE_SMOKESMALL";
	case IMAGE_SMOKEMISSILE_ID: return "IMAGE_SMOKEMISSILE";
	case IMAGE_WARPHOLE_ID: return "IMAGE_WARPHOLE";
	case IMAGE_WARPGLOW_ID: return "IMAGE_WARPGLOW";
	case IMAGE_EGGPIECES_ID: return "IMAGE_EGGPIECES";
	case IMAGE_EGGSHARDS_ID: return "IMAGE_EGGSHARDS";
	case IMAGE_EGGCRACK1_ID: return "IMAGE_EGGCRACK1";
	case IMAGE_EGGCRACK2_ID: return "IMAGE_EGGCRACK2";
	case IMAGE_BUBBULATOR_ID: return "IMAGE_BUBBULATOR";
	case IMAGE_STOREBACKDROPS_ID: return "IMAGE_STOREBACKDROPS";
	case IMAGE_WAVESIDE_ID: return "IMAGE_WAVESIDE";
	case IMAGE_WAVE_ID: return "IMAGE_WAVE";
	case IMAGE_LASERUPGRADES_ID: return "IMAGE_LASERUPGRADES";
	case IMAGE_MISSILE_ID: return "IMAGE_MISSILE";
	case IMAGE_AQUARIUM1_ID: return "IMAGE_AQUARIUM1";
	case IMAGE_AQUARIUM2_ID: return "IMAGE_AQUARIUM2";
	case IMAGE_AQUARIUM3_ID: return "IMAGE_AQUARIUM3";
	case IMAGE_AQUARIUM4_ID: return "IMAGE_AQUARIUM4";
	case IMAGE_AQUARIUM5_ID: return "IMAGE_AQUARIUM5";
	case IMAGE_AQUARIUM6_ID: return "IMAGE_AQUARIUM6";
	case IMAGE_TANKMASK1_ID: return "IMAGE_TANKMASK1";
	case IMAGE_TANKMASK2_ID: return "IMAGE_TANKMASK2";
	case IMAGE_TANKMASK3_ID: return "IMAGE_TANKMASK3";
	case IMAGE_TANKMASK4_ID: return "IMAGE_TANKMASK4";
	case IMAGE_TANKMASK5_ID: return "IMAGE_TANKMASK5";
	case IMAGE_TANKMASK6_ID: return "IMAGE_TANKMASK6";
	case IMAGE_SMALLTURN_ID: return "IMAGE_SMALLTURN";
	case IMAGE_HUNGRYTURN_ID: return "IMAGE_HUNGRYTURN";
	case IMAGE_HUNGRYEAT_ID: return "IMAGE_HUNGRYEAT";
	case IMAGE_SIMTURN1_ID: return "IMAGE_SIMTURN1";
	case IMAGE_SIMTURN2_ID: return "IMAGE_SIMTURN2";
	case IMAGE_SIMTURN3_ID: return "IMAGE_SIMTURN3";
	case IMAGE_SMALLEAT_ID: return "IMAGE_SMALLEAT";
	case IMAGE_SMALLDIE_ID: return "IMAGE_SMALLDIE";
	case IMAGE_HUNGRYSWIM_ID: return "IMAGE_HUNGRYSWIM";
	case IMAGE_HUNGRYBREEDER_ID: return "IMAGE_HUNGRYBREEDER";
	case IMAGE_SIMEAT1_ID: return "IMAGE_SIMEAT1";
	case IMAGE_SIMEAT2_ID: return "IMAGE_SIMEAT2";
	case IMAGE_SIMEAT3_ID: return "IMAGE_SIMEAT3";
	case IMAGE_SIMSWIM1_ID: return "IMAGE_SIMSWIM1";
	case IMAGE_SIMSWIM2_ID: return "IMAGE_SIMSWIM2";
	case IMAGE_SIMSWIM3_ID: return "IMAGE_SIMSWIM3";
	case IMAGE_SIMCARNIVORE_ID: return "IMAGE_SIMCARNIVORE";
	case IMAGE_TANKLIGHTING_ID: return "IMAGE_TANKLIGHTING";
	case IMAGE_SYLV_ID: return "IMAGE_SYLV";
	case IMAGE_BALROG_ID: return "IMAGE_BALROG";
	case IMAGE_GUS_ID: return "IMAGE_GUS";
	case IMAGE_DESTRUCTOR_ID: return "IMAGE_DESTRUCTOR";
	case IMAGE_ULYSSES_ID: return "IMAGE_ULYSSES";
	case IMAGE_PSYCHOSQUID_ID: return "IMAGE_PSYCHOSQUID";
	case IMAGE_BILATERUS_ID: return "IMAGE_BILATERUS";
	case IMAGE_MINISYLV_ID: return "IMAGE_MINISYLV";
	case IMAGE_BOSS_ID: return "IMAGE_BOSS";
	case IMAGE_HALO_ID: return "IMAGE_HALO";
	case IMAGE_GUMBOLIGHT_ID: return "IMAGE_GUMBOLIGHT";
	case IMAGE_AMPCHARGE_ID: return "IMAGE_AMPCHARGE";
	case IMAGE_NIKOTOWER_ID: return "IMAGE_NIKOTOWER";
	case IMAGE_STINKY_ID: return "IMAGE_STINKY";
	case IMAGE_NIKO_ID: return "IMAGE_NIKO";
	case IMAGE_ITCHY_ID: return "IMAGE_ITCHY";
	case IMAGE_PREGO_ID: return "IMAGE_PREGO";
	case IMAGE_ZORF_ID: return "IMAGE_ZORF";
	case IMAGE_CLYDE_ID: return "IMAGE_CLYDE";
	case IMAGE_VERT_ID: return "IMAGE_VERT";
	case IMAGE_RUFUS_ID: return "IMAGE_RUFUS";
	case IMAGE_MERYL_ID: return "IMAGE_MERYL";
	case IMAGE_WADSWORTH_ID: return "IMAGE_WADSWORTH";
	case IMAGE_SEYMOUR_ID: return "IMAGE_SEYMOUR";
	case IMAGE_SHRAPNEL_ID: return "IMAGE_SHRAPNEL";
	case IMAGE_GUMBO_ID: return "IMAGE_GUMBO";
	case IMAGE_BLIP_ID: return "IMAGE_BLIP";
	case IMAGE_RHUBARB_ID: return "IMAGE_RHUBARB";
	case IMAGE_NIMBUS_ID: return "IMAGE_NIMBUS";
	case IMAGE_AMP_ID: return "IMAGE_AMP";
	case IMAGE_GASH_ID: return "IMAGE_GASH";
	case IMAGE_ANGIE_ID: return "IMAGE_ANGIE";
	case IMAGE_PRESTO_ID: return "IMAGE_PRESTO";
	case IMAGE_BRINKLEY_ID: return "IMAGE_BRINKLEY";
	case IMAGE_NOSTRADAMUS_ID: return "IMAGE_NOSTRADAMUS";
	case IMAGE_STANLEY_ID: return "IMAGE_STANLEY";
	case IMAGE_WALTER_ID: return "IMAGE_WALTER";
	case IMAGE_SMALLSWIM_ID: return "IMAGE_SMALLSWIM";
	case IMAGE_GRUBBER_ID: return "IMAGE_GRUBBER";
	case IMAGE_STARCATCHER_ID: return "IMAGE_STARCATCHER";
	case IMAGE_GEKKO_ID: return "IMAGE_GEKKO";
	case IMAGE_BREEDER_ID: return "IMAGE_BREEDER";
	case IMAGE_ULTRA_ID: return "IMAGE_ULTRA";
	case IMAGE_SCL_STINKY_ID: return "IMAGE_SCL_STINKY";
	case IMAGE_SCL_NIKO_ID: return "IMAGE_SCL_NIKO";
	case IMAGE_SCL_ITCHY_ID: return "IMAGE_SCL_ITCHY";
	case IMAGE_SCL_PREGO_ID: return "IMAGE_SCL_PREGO";
	case IMAGE_SCL_ZORF_ID: return "IMAGE_SCL_ZORF";
	case IMAGE_SCL_CLYDE_ID: return "IMAGE_SCL_CLYDE";
	case IMAGE_SCL_VERT_ID: return "IMAGE_SCL_VERT";
	case IMAGE_SCL_RUFUS_ID: return "IMAGE_SCL_RUFUS";
	case IMAGE_SCL_MERYL_ID: return "IMAGE_SCL_MERYL";
	case IMAGE_SCL_WADSWORTH_ID: return "IMAGE_SCL_WADSWORTH";
	case IMAGE_SCL_SEYMOUR_ID: return "IMAGE_SCL_SEYMOUR";
	case IMAGE_SCL_SHRAPNEL_ID: return "IMAGE_SCL_SHRAPNEL";
	case IMAGE_SCL_GUMBO_ID: return "IMAGE_SCL_GUMBO";
	case IMAGE_SCL_BLIP_ID: return "IMAGE_SCL_BLIP";
	case IMAGE_SCL_RHUBARB_ID: return "IMAGE_SCL_RHUBARB";
	case IMAGE_SCL_NIMBUS_ID: return "IMAGE_SCL_NIMBUS";
	case IMAGE_SCL_AMP_ID: return "IMAGE_SCL_AMP";
	case IMAGE_SCL_GASH_ID: return "IMAGE_SCL_GASH";
	case IMAGE_SCL_ANGIE_ID: return "IMAGE_SCL_ANGIE";
	case IMAGE_SCL_PRESTO_ID: return "IMAGE_SCL_PRESTO";
	case IMAGE_SCL_BRINKLEY_ID: return "IMAGE_SCL_BRINKLEY";
	case IMAGE_SCL_NOSTRADAMUS_ID: return "IMAGE_SCL_NOSTRADAMUS";
	case IMAGE_SCL_STANLEY_ID: return "IMAGE_SCL_STANLEY";
	case IMAGE_SCL_WALTER_ID: return "IMAGE_SCL_WALTER";
	case IMAGE_SCL_OSCAR_ID: return "IMAGE_SCL_OSCAR";
	case IMAGE_SCL_GRUBBER_ID: return "IMAGE_SCL_GRUBBER";
	case IMAGE_SCL_STARCATCHER_ID: return "IMAGE_SCL_STARCATCHER";
	case IMAGE_SCL_GEKKO_ID: return "IMAGE_SCL_GEKKO";
	case IMAGE_SCL_BREEDER_ID: return "IMAGE_SCL_BREEDER";
	case IMAGE_SCL_ULTRA_ID: return "IMAGE_SCL_ULTRA";
	case SOUND_AWOOGA_ID: return "SOUND_AWOOGA";
	case SOUND_APPLAUSE_ID: return "SOUND_APPLAUSE";
	case SOUND_BABY_ID: return "SOUND_BABY";
	case SOUND_BONUSCOUNT_ID: return "SOUND_BONUSCOUNT";
	case SOUND_TONE_ID: return "SOUND_TONE";
	case SOUND_TONELO_ID: return "SOUND_TONELO";
	case SOUND_TONEHI_ID: return "SOUND_TONEHI";
	case SOUND_TONESUPERHI_ID: return "SOUND_TONESUPERHI";
	case SOUND_PRIMALSCREAM_ID: return "SOUND_PRIMALSCREAM";
	case SOUND_BONUSCOLLECT_ID: return "SOUND_BONUSCOLLECT";
	case SOUND_BUBBLES_ID: return "SOUND_BUBBLES";
	case SOUND_BUY_ID: return "SOUND_BUY";
	case SOUND_BUZZER_ID: return "SOUND_BUZZER";
	case SOUND_CHOMP_ID: return "SOUND_CHOMP";
	case SOUND_CHOMP2_ID: return "SOUND_CHOMP2";
	case SOUND_CROWNED_ID: return "SOUND_CROWNED";
	case SOUND_DIAMOND_ID: return "SOUND_DIAMOND";
	case SOUND_DIE_ID: return "SOUND_DIE";
	case SOUND_DROPFOOD_ID: return "SOUND_DROPFOOD";
	case SOUND_EEL1_ID: return "SOUND_EEL1";
	case SOUND_EEL2_ID: return "SOUND_EEL2";
	case SOUND_EEL3_ID: return "SOUND_EEL3";
	case SOUND_EVILLAFF_ID: return "SOUND_EVILLAFF";
	case SOUND_EXPLODE_ID: return "SOUND_EXPLODE";
	case SOUND_EXPLOSION1_ID: return "SOUND_EXPLOSION1";
	case SOUND_EXPLOSION4_ID: return "SOUND_EXPLOSION4";
	case SOUND_FART_ID: return "SOUND_FART";
	case SOUND_FART2_ID: return "SOUND_FART2";
	case SOUND_GROW_ID: return "SOUND_GROW";
	case SOUND_GUFFAW_ID: return "SOUND_GUFFAW";
	case SOUND_HATCH_ID: return "SOUND_HATCH";
	case SOUND_HEAL_ID: return "SOUND_HEAL";
	case SOUND_HIT_ID: return "SOUND_HIT";
	case SOUND_INTERFER_ID: return "SOUND_INTERFER";
	case SOUND_MISSLE_ID: return "SOUND_MISSLE";
	case SOUND_NIKOOPEN_ID: return "SOUND_NIKOOPEN";
	case SOUND_NIKOCLOSE_ID: return "SOUND_NIKOCLOSE";
	case SOUND_PEARL_ID: return "SOUND_PEARL";
	case SOUND_POINTS_ID: return "SOUND_POINTS";
	case SOUND_POINTS2_ID: return "SOUND_POINTS2";
	case SOUND_POINTS3_ID: return "SOUND_POINTS3";
	case SOUND_POINTS4_ID: return "SOUND_POINTS4";
	case SOUND_PUNCH_ID: return "SOUND_PUNCH";
	case SOUND_RATTLE_ID: return "SOUND_RATTLE";
	case SOUND_RICOCHET_ID: return "SOUND_RICOCHET";
	case SOUND_ROAR_ID: return "SOUND_ROAR";
	case SOUND_ROAR2_ID: return "SOUND_ROAR2";
	case SOUND_ROAR3_ID: return "SOUND_ROAR3";
	case SOUND_SFX_ID: return "SOUND_SFX";
	case SOUND_SING_ID: return "SOUND_SING";
	case SOUND_SLURP_ID: return "SOUND_SLURP";
	case SOUND_SLURP2_ID: return "SOUND_SLURP2";
	case SOUND_SLURP3_ID: return "SOUND_SLURP3";
	case SOUND_SNEEZE_ID: return "SOUND_SNEEZE";
	case SOUND_SONAR_ID: return "SOUND_SONAR";
	case SOUND_SPLASH_ID: return "SOUND_SPLASH";
	case SOUND_SPLASH2_ID: return "SOUND_SPLASH2";
	case SOUND_SPLASH3_ID: return "SOUND_SPLASH3";
	case SOUND_SPLASHBIG_ID: return "SOUND_SPLASHBIG";
	case SOUND_TAPGLASS_ID: return "SOUND_TAPGLASS";
	case SOUND_TREASURE_ID: return "SOUND_TREASURE";
	case SOUND_UNLEASH_ID: return "SOUND_UNLEASH";
	case SOUND_ZAP_ID: return "SOUND_ZAP";
	case SOUND_ZZAM_ID: return "SOUND_ZZAM";
	default: return "";
	}
}

