#ifndef __Res_H__
#define __Res_H__

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;

	Image* LoadImageById(ResourceManager* theManager, int theId);
	void ReplaceImageById(ResourceManager* theManager, int theId, Image* theImage);
	bool ExtractResourcesByName(ResourceManager* theManager, const char* theName);

	// Init Resources
	bool ExtractInitResources(ResourceManager* theMgr);
	extern Font* FONT_PICO129;
	extern Font* FONT_JUNGLEFEVER10OUTLINE;
	extern Font* FONT_JUNGLEFEVER17OUTLINE;
	extern Image* IMAGE_BLANK;
	extern Image* IMAGE_CURSOR_DRAGGING;
	extern Image* IMAGE_CURSOR_HAND;
	extern Image* IMAGE_CURSOR_POINTER;
	extern Image* IMAGE_CURSOR_TEXT;
	extern Image* IMAGE_LOADERBAR;
	extern Image* IMAGE_LOADERBARLOADING;
	extern Image* IMAGE_LOADERBAROVER;
	extern Image* IMAGE_LOADERPLAY;
	extern Image* IMAGE_TITLEPAGE;
	extern Image* IMAGE_TITLEPAGEMASK;
	extern int SOUND_BUTTONCLICK;

	// LoadingThread Resources
	bool ExtractLoadingThreadResources(ResourceManager* theMgr);
	extern Image* IMAGE_AA_BEAM;
	extern Image* IMAGE_AA_BOTTOM;
	extern Image* IMAGE_AA_GLOW;
	extern Image* IMAGE_AA_STORE;
	extern Image* IMAGE_AA_TOP1;
	extern Image* IMAGE_AA_TOP2;
	extern Image* IMAGE_AMP;
	extern Image* IMAGE_AMPCHARGE;
	extern Image* IMAGE_ANGIE;
	extern Image* IMAGE_AQUARIUM1;
	extern Image* IMAGE_AQUARIUM2;
	extern Image* IMAGE_AQUARIUM3;
	extern Image* IMAGE_AQUARIUM4;
	extern Image* IMAGE_AQUARIUM5;
	extern Image* IMAGE_AQUARIUM6;
	extern Image* IMAGE_BALLS;
	extern Image* IMAGE_BALROG;
	extern Image* IMAGE_BATTLETANKBUTTON;
	extern Image* IMAGE_BATTLETANKBUTTOND;
	extern Image* IMAGE_BILATERUS;
	extern Image* IMAGE_BLIP;
	extern Image* IMAGE_BOLT;
	extern Image* IMAGE_BONUS1;
	extern Image* IMAGE_BONUS2;
	extern Image* IMAGE_BONUS3;
	extern Image* IMAGE_BONUSAWARD2;
	extern Image* IMAGE_BONUSAWARD;
	extern Image* IMAGE_BONUSBUCKET;
	extern Image* IMAGE_BONUSBUTTONOVERLAY;
	extern Image* IMAGE_BOSS;
	extern Image* IMAGE_BREEDER;
	extern Image* IMAGE_BRINKLEY;
	extern Image* IMAGE_BUBBLES;
	extern Image* IMAGE_BUBBULATOR;
	extern Image* IMAGE_BUBBULATOR_STORE;
	extern Image* IMAGE_CENTERBUTTON;
	extern Image* IMAGE_CHECKED;
	extern Image* IMAGE_CHICKEN;
	extern Image* IMAGE_CHOMP;
	extern Image* IMAGE_CLYDE;
	extern Image* IMAGE_CROSSHAIR;
	extern Image* IMAGE_DESTRUCTOR;
	extern Image* IMAGE_EGGBRINKLEY;
	extern Image* IMAGE_EGGCRACK1;
	extern Image* IMAGE_EGGCRACK2;
	extern Image* IMAGE_EGGNOSTRADAMUS;
	extern Image* IMAGE_EGGPIECES;
	extern Image* IMAGE_EGGSHARDS;
	extern Image* IMAGE_EGGSTANLEY;
	extern Image* IMAGE_EGGWALTER;
	extern Image* IMAGE_ENERGYBALL;
	extern Image* IMAGE_EXPLOSION;
	extern Image* IMAGE_EXPLOSIONSMALL;
	extern Image* IMAGE_EXPLOSIONTINY;
	extern Image* IMAGE_FATBUTTON;
	extern Image* IMAGE_FISHBOX;
	extern Image* IMAGE_FISHBOXBUTTON;
	extern Image* IMAGE_FOOD;
	extern Image* IMAGE_GASH;
	extern Image* IMAGE_GEKKO;
	extern Image* IMAGE_GRUBBER;
	extern Image* IMAGE_GUMBO;
	extern Image* IMAGE_GUMBOLIGHT;
	extern Image* IMAGE_GUS;
	extern Image* IMAGE_HALO;
	extern Image* IMAGE_HATCHANIMATION;
	extern Image* IMAGE_HATCHREFLECTION;
	extern Image* IMAGE_HATCHSCREEN;
	extern Image* IMAGE_HEALTHBAR;
	extern Image* IMAGE_HEALTHBARTUBE;
	extern Image* IMAGE_HELPALIEN;
	extern Image* IMAGE_HELPARROW;
	extern Image* IMAGE_HELPPETCHOOSE;
	extern Image* IMAGE_HELPSCREENSAVER;
	extern Image* IMAGE_HELPSHELL;
	extern Image* IMAGE_HORZCREASE;
	extern Image* IMAGE_HUNGRYBREEDER;
	extern Image* IMAGE_HUNGRYEAT;
	extern Image* IMAGE_HUNGRYSWIM;
	extern Image* IMAGE_HUNGRYTURN;
	extern Image* IMAGE_ICECREAM;
	extern Image* IMAGE_ITCHY;
	extern Image* IMAGE_LASERS;
	extern Image* IMAGE_LASERUPGRADES;
	extern Image* IMAGE_LEFTBUTTON;
	extern Image* IMAGE_MAINBUTTON;
	extern Image* IMAGE_MENUBAR;
	extern Image* IMAGE_MENUBTND2;
	extern Image* IMAGE_MENUBTND;
	extern Image* IMAGE_MENUBTNO;
	extern Image* IMAGE_MENUBTNU;
	extern Image* IMAGE_MENUBUTTONREFLECTION;
	extern Image* IMAGE_MERYL;
	extern Image* IMAGE_MERYLBLINK;
	extern Image* IMAGE_MERYLLIPS;
	extern Image* IMAGE_MERYLTAIL;
	extern Image* IMAGE_MIDDLEBUTTON;
	extern Image* IMAGE_MIDDLEBUTTOND;
	extern Image* IMAGE_MINISYLV;
	extern Image* IMAGE_MISCITEMS;
	extern Image* IMAGE_MISSILE;
	extern Image* IMAGE_MONEY;
	extern Image* IMAGE_MONEYBAG;
	extern Image* IMAGE_MONEYFLASH;
	extern Image* IMAGE_NIKO;
	extern Image* IMAGE_NIKOTOWER;
	extern Image* IMAGE_NIMBUS;
	extern Image* IMAGE_NOSTRADAMUS;
	extern Image* IMAGE_OPTIONSBUTTON;
	extern Image* IMAGE_OPTIONSBUTTOND;
	extern Image* IMAGE_PEANUT;
	extern Image* IMAGE_PEARL;
	extern Image* IMAGE_PETBTNO;
	extern Image* IMAGE_PETBTNU;
	extern Image* IMAGE_PETBUTTON;
	extern Image* IMAGE_PETBUTTONHOLE;
	extern Image* IMAGE_PETBUTTONREFLECT;
	extern Image* IMAGE_PETBUTTONRING;
	extern Image* IMAGE_PETLIMITEGG;
	extern Image* IMAGE_PIZZA;
	extern Image* IMAGE_PREGO;
	extern Image* IMAGE_PRESTO;
	extern Image* IMAGE_PSYCHOSQUID;
	extern Image* IMAGE_RHUBARB;
	extern Image* IMAGE_RIGHTBUTTON;
	extern Image* IMAGE_RUFUS;
	extern Image* IMAGE_SCL_AMP;
	extern Image* IMAGE_SCL_ANGIE;
	extern Image* IMAGE_SCL_BLIP;
	extern Image* IMAGE_SCL_BREEDER;
	extern Image* IMAGE_SCL_BRINKLEY;
	extern Image* IMAGE_SCL_CLYDE;
	extern Image* IMAGE_SCL_GASH;
	extern Image* IMAGE_SCL_GEKKO;
	extern Image* IMAGE_SCL_GRUBBER;
	extern Image* IMAGE_SCL_GUMBO;
	extern Image* IMAGE_SCL_ITCHY;
	extern Image* IMAGE_SCL_MERYL;
	extern Image* IMAGE_SCL_NIKO;
	extern Image* IMAGE_SCL_NIMBUS;
	extern Image* IMAGE_SCL_NOSTRADAMUS;
	extern Image* IMAGE_SCL_OSCAR;
	extern Image* IMAGE_SCL_PREGO;
	extern Image* IMAGE_SCL_PRESTO;
	extern Image* IMAGE_SCL_RHUBARB;
	extern Image* IMAGE_SCL_RUFUS;
	extern Image* IMAGE_SCL_SEYMOUR;
	extern Image* IMAGE_SCL_SHRAPNEL;
	extern Image* IMAGE_SCL_STANLEY;
	extern Image* IMAGE_SCL_STARCATCHER;
	extern Image* IMAGE_SCL_STINKY;
	extern Image* IMAGE_SCL_ULTRA;
	extern Image* IMAGE_SCL_VERT;
	extern Image* IMAGE_SCL_WADSWORTH;
	extern Image* IMAGE_SCL_WALTER;
	extern Image* IMAGE_SCL_ZORF;
	extern Image* IMAGE_SCREENBACK;
	extern Image* IMAGE_SCREENTITLE;
	extern Image* IMAGE_SCREENTITLEHOLE;
	extern Image* IMAGE_SELECTORSCREEN;
	extern Image* IMAGE_SELECTORSPEECHBUBBLE;
	extern Image* IMAGE_SEYMOUR;
	extern Image* IMAGE_SHADOW;
	extern Image* IMAGE_SHELLS;
	extern Image* IMAGE_SHRAPNEL;
	extern Image* IMAGE_SIMCARNIVORE;
	extern Image* IMAGE_SIMEAT1;
	extern Image* IMAGE_SIMEAT2;
	extern Image* IMAGE_SIMEAT3;
	extern Image* IMAGE_SIMSWIM1;
	extern Image* IMAGE_SIMSWIM2;
	extern Image* IMAGE_SIMSWIM3;
	extern Image* IMAGE_SIMTURN1;
	extern Image* IMAGE_SIMTURN2;
	extern Image* IMAGE_SIMTURN3;
	extern Image* IMAGE_SLIDERTHUMB;
	extern Image* IMAGE_SLIDERTRACK;
	extern Image* IMAGE_SMALLDIE;
	extern Image* IMAGE_SMALLEAT;
	extern Image* IMAGE_SMALLSWIM;
	extern Image* IMAGE_SMALLTURN;
	extern Image* IMAGE_SMOKEMISSILE;
	extern Image* IMAGE_SMOKESMALL;
	extern Image* IMAGE_SMOKETINY;
	extern Image* IMAGE_SPARKLE;
	extern Image* IMAGE_SPARKS;
	extern Image* IMAGE_SPEECHBUBBLE;
	extern Image* IMAGE_STANLEY;
	extern Image* IMAGE_STARCATCHER;
	extern Image* IMAGE_STINKY;
	extern Image* IMAGE_STOREBACKDROPS;
	extern Image* IMAGE_STORELEFTBUTTON;
	extern Image* IMAGE_STORELEFTHILIGHT;
	extern Image* IMAGE_STORERIGHTBUTTON;
	extern Image* IMAGE_STORERIGHTHILIGHT;
	extern Image* IMAGE_STORESCREEN;
	extern Image* IMAGE_STORESHELL;
	extern Image* IMAGE_STORETOPBUTTON;
	extern Image* IMAGE_STORETOPHILIGHT;
	extern Image* IMAGE_SYLV;
	extern Image* IMAGE_TANKBACKDROP1;
	extern Image* IMAGE_TANKBACKDROP2;
	extern Image* IMAGE_TANKBACKDROP3;
	extern Image* IMAGE_TANKBACKDROP4;
	extern Image* IMAGE_TANKBACKDROP5;
	extern Image* IMAGE_TANKBACKDROP6;
	extern Image* IMAGE_TANKCHOOSER;
	extern Image* IMAGE_TANKLIGHTING;
	extern Image* IMAGE_TANKMASK1;
	extern Image* IMAGE_TANKMASK2;
	extern Image* IMAGE_TANKMASK3;
	extern Image* IMAGE_TANKMASK4;
	extern Image* IMAGE_TANKMASK5;
	extern Image* IMAGE_TANKMASK6;
	extern Image* IMAGE_TROPHYBAR;
	extern Image* IMAGE_TROPHYBUTTONS;
	extern Image* IMAGE_ULTRA;
	extern Image* IMAGE_ULYSSES;
	extern Image* IMAGE_UNCHECKED;
	extern Image* IMAGE_VERT;
	extern Image* IMAGE_VERTCREASE;
	extern Image* IMAGE_WADSWORTH;
	extern Image* IMAGE_WAIT_BAR;
	extern Image* IMAGE_WALTER;
	extern Image* IMAGE_WARPGLOW;
	extern Image* IMAGE_WARPHOLE;
	extern Image* IMAGE_WAVE;
	extern Image* IMAGE_WAVESIDE;
	extern Image* IMAGE_WELCOMEBACK;
	extern Image* IMAGE_WELCOMETO;
	extern Image* IMAGE_ZORF;
	extern Image* IMAGE_ZZZ;
	extern int SOUND_APPLAUSE;
	extern int SOUND_AWOOGA;
	extern int SOUND_BABY;
	extern int SOUND_BONUSCOLLECT;
	extern int SOUND_BONUSCOUNT;
	extern int SOUND_BUBBLES;
	extern int SOUND_BUY;
	extern int SOUND_BUZZER;
	extern int SOUND_CHOMP2;
	extern int SOUND_CHOMP;
	extern int SOUND_CROWNED;
	extern int SOUND_DIAMOND;
	extern int SOUND_DIE;
	extern int SOUND_DROPFOOD;
	extern int SOUND_EEL1;
	extern int SOUND_EEL2;
	extern int SOUND_EEL3;
	extern int SOUND_EVILLAFF;
	extern int SOUND_EXPLODE;
	extern int SOUND_EXPLOSION1;
	extern int SOUND_EXPLOSION4;
	extern int SOUND_FART2;
	extern int SOUND_FART;
	extern int SOUND_GROW;
	extern int SOUND_GUFFAW;
	extern int SOUND_HATCH;
	extern int SOUND_HEAL;
	extern int SOUND_HIT;
	extern int SOUND_INTERFER;
	extern int SOUND_MISSLE;
	extern int SOUND_NIKOCLOSE;
	extern int SOUND_NIKOOPEN;
	extern int SOUND_PEARL;
	extern int SOUND_POINTS2;
	extern int SOUND_POINTS3;
	extern int SOUND_POINTS4;
	extern int SOUND_POINTS;
	extern int SOUND_PRIMALSCREAM;
	extern int SOUND_PUNCH;
	extern int SOUND_RATTLE;
	extern int SOUND_RICOCHET;
	extern int SOUND_ROAR2;
	extern int SOUND_ROAR3;
	extern int SOUND_ROAR;
	extern int SOUND_SFX;
	extern int SOUND_SING;
	extern int SOUND_SLURP2;
	extern int SOUND_SLURP3;
	extern int SOUND_SLURP;
	extern int SOUND_SNEEZE;
	extern int SOUND_SONAR;
	extern int SOUND_SPLASH2;
	extern int SOUND_SPLASH3;
	extern int SOUND_SPLASH;
	extern int SOUND_SPLASHBIG;
	extern int SOUND_TAPGLASS;
	extern int SOUND_TONE;
	extern int SOUND_TONEHI;
	extern int SOUND_TONELO;
	extern int SOUND_TONESUPERHI;
	extern int SOUND_TREASURE;
	extern int SOUND_UNLEASH;
	extern int SOUND_ZAP;
	extern int SOUND_ZZAM;

	// Register Resources
	bool ExtractRegisterResources(ResourceManager* theMgr);
	extern Font* FONT_BLAMBOTPRO15;
	extern Font* FONT_BLAMBOTPRO8;
	extern Font* FONT_CONTINUUMBOLD12;
	extern Font* FONT_CONTINUUMBOLD12OUTLINE;
	extern Font* FONT_CONTINUUMBOLD14;
	extern Font* FONT_CONTINUUMBOLD14OUTLINE;
	extern Font* FONT_JUNGLEFEVER12OUTLINE;
	extern Font* FONT_JUNGLEFEVER15OUTLINE;
	extern Font* FONT_LIDDIE12;
	extern Font* FONT_LIDDIE15;
	extern Font* FONT_LIDDIE18;
	extern Font* FONT_TINY;
	extern Font* FONT_TINYBOLD;
	extern Image* IMAGE_DIALOG;
	extern Image* IMAGE_DIALOGBUTTON;
	extern Image* IMAGE_EDITBOX;

	enum ResourceId
	{
		IMAGE_CURSOR_POINTER_ID,
		IMAGE_CURSOR_HAND_ID,
		IMAGE_CURSOR_DRAGGING_ID,
		IMAGE_CURSOR_TEXT_ID,
		IMAGE_BLANK_ID,
		IMAGE_TITLEPAGE_ID,
		IMAGE_TITLEPAGEMASK_ID,
		IMAGE_LOADERBAR_ID,
		IMAGE_LOADERBAROVER_ID,
		IMAGE_LOADERBARLOADING_ID,
		IMAGE_LOADERPLAY_ID,
		FONT_JUNGLEFEVER10OUTLINE_ID,
		FONT_JUNGLEFEVER17OUTLINE_ID,
		SOUND_BUTTONCLICK_ID,
		FONT_LIDDIE12_ID,
		FONT_LIDDIE15_ID,
		FONT_LIDDIE18_ID,
		FONT_JUNGLEFEVER12OUTLINE_ID,
		FONT_JUNGLEFEVER15OUTLINE_ID,
		FONT_BLAMBOTPRO8_ID,
		FONT_BLAMBOTPRO15_ID,
		FONT_TINY_ID,
		FONT_TINYBOLD_ID,
		FONT_CONTINUUMBOLD12_ID,
		FONT_CONTINUUMBOLD12OUTLINE_ID,
		FONT_CONTINUUMBOLD14_ID,
		FONT_CONTINUUMBOLD14OUTLINE_ID,
		IMAGE_DIALOG_ID,
		IMAGE_DIALOGBUTTON_ID,
		IMAGE_EDITBOX_ID,
		IMAGE_SELECTORSCREEN_ID,
		IMAGE_STORESCREEN_ID,
		IMAGE_HATCHSCREEN_ID,
		IMAGE_MAINBUTTON_ID,
		IMAGE_LEFTBUTTON_ID,
		IMAGE_RIGHTBUTTON_ID,
		IMAGE_CENTERBUTTON_ID,
		IMAGE_SCREENBACK_ID,
		IMAGE_SCREENTITLE_ID,
		IMAGE_SCREENTITLEHOLE_ID,
		IMAGE_FISHBOX_ID,
		IMAGE_FISHBOXBUTTON_ID,
		IMAGE_PETBUTTON_ID,
		IMAGE_PETBUTTONRING_ID,
		IMAGE_PETBUTTONREFLECT_ID,
		IMAGE_PETBUTTONHOLE_ID,
		IMAGE_STORELEFTBUTTON_ID,
		IMAGE_STORETOPBUTTON_ID,
		IMAGE_STORERIGHTBUTTON_ID,
		IMAGE_STORELEFTHILIGHT_ID,
		IMAGE_STORETOPHILIGHT_ID,
		IMAGE_STORERIGHTHILIGHT_ID,
		IMAGE_BATTLETANKBUTTON_ID,
		IMAGE_BATTLETANKBUTTOND_ID,
		IMAGE_MIDDLEBUTTON_ID,
		IMAGE_MIDDLEBUTTOND_ID,
		IMAGE_OPTIONSBUTTON_ID,
		IMAGE_OPTIONSBUTTOND_ID,
		IMAGE_MENUBTND_ID,
		IMAGE_MENUBTND2_ID,
		IMAGE_MENUBTNU_ID,
		IMAGE_MENUBTNO_ID,
		IMAGE_PETBTNU_ID,
		IMAGE_PETBTNO_ID,
		IMAGE_UNCHECKED_ID,
		IMAGE_CHECKED_ID,
		IMAGE_SLIDERTRACK_ID,
		IMAGE_SLIDERTHUMB_ID,
		IMAGE_WAIT_BAR_ID,
		IMAGE_MENUBAR_ID,
		IMAGE_MONEYFLASH_ID,
		IMAGE_MENUBUTTONREFLECTION_ID,
		IMAGE_TROPHYBAR_ID,
		IMAGE_SPEECHBUBBLE_ID,
		IMAGE_SHADOW_ID,
		IMAGE_HATCHREFLECTION_ID,
		IMAGE_SELECTORSPEECHBUBBLE_ID,
		IMAGE_HELPARROW_ID,
		IMAGE_TANKCHOOSER_ID,
		IMAGE_BOLT_ID,
		IMAGE_HORZCREASE_ID,
		IMAGE_VERTCREASE_ID,
		IMAGE_BUBBULATOR_STORE_ID,
		IMAGE_AA_STORE_ID,
		IMAGE_ZZZ_ID,
		IMAGE_BONUSBUCKET_ID,
		IMAGE_HELPALIEN_ID,
		IMAGE_HELPPETCHOOSE_ID,
		IMAGE_HELPSCREENSAVER_ID,
		IMAGE_BONUS1_ID,
		IMAGE_BONUS2_ID,
		IMAGE_BONUS3_ID,
		IMAGE_WELCOMETO_ID,
		IMAGE_WELCOMEBACK_ID,
		IMAGE_PIZZA_ID,
		IMAGE_ICECREAM_ID,
		IMAGE_CHICKEN_ID,
		IMAGE_SPARKLE_ID,
		IMAGE_TANKBACKDROP1_ID,
		IMAGE_TANKBACKDROP2_ID,
		IMAGE_TANKBACKDROP3_ID,
		IMAGE_TANKBACKDROP4_ID,
		IMAGE_TANKBACKDROP5_ID,
		IMAGE_TANKBACKDROP6_ID,
		IMAGE_HEALTHBAR_ID,
		IMAGE_HEALTHBARTUBE_ID,
		IMAGE_HELPSHELL_ID,
		IMAGE_STORESHELL_ID,
		IMAGE_BONUSBUTTONOVERLAY_ID,
		IMAGE_FATBUTTON_ID,
		IMAGE_EGGBRINKLEY_ID,
		IMAGE_EGGNOSTRADAMUS_ID,
		IMAGE_EGGSTANLEY_ID,
		IMAGE_EGGWALTER_ID,
		IMAGE_PETLIMITEGG_ID,
		IMAGE_BONUSAWARD_ID,
		IMAGE_BONUSAWARD2_ID,
		IMAGE_AA_BEAM_ID,
		IMAGE_AA_GLOW_ID,
		IMAGE_AA_TOP1_ID,
		IMAGE_AA_TOP2_ID,
		IMAGE_AA_BOTTOM_ID,
		IMAGE_SPARKS_ID,
		IMAGE_ENERGYBALL_ID,
		IMAGE_CHOMP_ID,
		IMAGE_LASERS_ID,
		IMAGE_BUBBLES_ID,
		IMAGE_MONEY_ID,
		IMAGE_PEARL_ID,
		IMAGE_PEANUT_ID,
		IMAGE_MISCITEMS_ID,
		IMAGE_SHELLS_ID,
		IMAGE_MONEYBAG_ID,
		IMAGE_FOOD_ID,
		IMAGE_BALLS_ID,
		IMAGE_MERYLLIPS_ID,
		IMAGE_MERYLBLINK_ID,
		IMAGE_MERYLTAIL_ID,
		IMAGE_CROSSHAIR_ID,
		IMAGE_HATCHANIMATION_ID,
		IMAGE_TROPHYBUTTONS_ID,
		IMAGE_EXPLOSION_ID,
		IMAGE_EXPLOSIONSMALL_ID,
		IMAGE_EXPLOSIONTINY_ID,
		IMAGE_SMOKETINY_ID,
		IMAGE_SMOKESMALL_ID,
		IMAGE_SMOKEMISSILE_ID,
		IMAGE_WARPHOLE_ID,
		IMAGE_WARPGLOW_ID,
		IMAGE_EGGPIECES_ID,
		IMAGE_EGGSHARDS_ID,
		IMAGE_EGGCRACK1_ID,
		IMAGE_EGGCRACK2_ID,
		IMAGE_BUBBULATOR_ID,
		IMAGE_STOREBACKDROPS_ID,
		IMAGE_WAVESIDE_ID,
		IMAGE_WAVE_ID,
		IMAGE_LASERUPGRADES_ID,
		IMAGE_MISSILE_ID,
		IMAGE_AQUARIUM1_ID,
		IMAGE_AQUARIUM2_ID,
		IMAGE_AQUARIUM3_ID,
		IMAGE_AQUARIUM4_ID,
		IMAGE_AQUARIUM5_ID,
		IMAGE_AQUARIUM6_ID,
		IMAGE_TANKMASK1_ID,
		IMAGE_TANKMASK2_ID,
		IMAGE_TANKMASK3_ID,
		IMAGE_TANKMASK4_ID,
		IMAGE_TANKMASK5_ID,
		IMAGE_TANKMASK6_ID,
		IMAGE_SMALLTURN_ID,
		IMAGE_HUNGRYTURN_ID,
		IMAGE_HUNGRYEAT_ID,
		IMAGE_SIMTURN1_ID,
		IMAGE_SIMTURN2_ID,
		IMAGE_SIMTURN3_ID,
		IMAGE_SMALLEAT_ID,
		IMAGE_SMALLDIE_ID,
		IMAGE_HUNGRYSWIM_ID,
		IMAGE_HUNGRYBREEDER_ID,
		IMAGE_SIMEAT1_ID,
		IMAGE_SIMEAT2_ID,
		IMAGE_SIMEAT3_ID,
		IMAGE_SIMSWIM1_ID,
		IMAGE_SIMSWIM2_ID,
		IMAGE_SIMSWIM3_ID,
		IMAGE_SIMCARNIVORE_ID,
		IMAGE_TANKLIGHTING_ID,
		IMAGE_SYLV_ID,
		IMAGE_BALROG_ID,
		IMAGE_GUS_ID,
		IMAGE_DESTRUCTOR_ID,
		IMAGE_ULYSSES_ID,
		IMAGE_PSYCHOSQUID_ID,
		IMAGE_BILATERUS_ID,
		IMAGE_MINISYLV_ID,
		IMAGE_BOSS_ID,
		IMAGE_HALO_ID,
		IMAGE_GUMBOLIGHT_ID,
		IMAGE_AMPCHARGE_ID,
		IMAGE_NIKOTOWER_ID,
		IMAGE_STINKY_ID,
		IMAGE_NIKO_ID,
		IMAGE_ITCHY_ID,
		IMAGE_PREGO_ID,
		IMAGE_ZORF_ID,
		IMAGE_CLYDE_ID,
		IMAGE_VERT_ID,
		IMAGE_RUFUS_ID,
		IMAGE_MERYL_ID,
		IMAGE_WADSWORTH_ID,
		IMAGE_SEYMOUR_ID,
		IMAGE_SHRAPNEL_ID,
		IMAGE_GUMBO_ID,
		IMAGE_BLIP_ID,
		IMAGE_RHUBARB_ID,
		IMAGE_NIMBUS_ID,
		IMAGE_AMP_ID,
		IMAGE_GASH_ID,
		IMAGE_ANGIE_ID,
		IMAGE_PRESTO_ID,
		IMAGE_BRINKLEY_ID,
		IMAGE_NOSTRADAMUS_ID,
		IMAGE_STANLEY_ID,
		IMAGE_WALTER_ID,
		IMAGE_SMALLSWIM_ID,
		IMAGE_GRUBBER_ID,
		IMAGE_STARCATCHER_ID,
		IMAGE_GEKKO_ID,
		IMAGE_BREEDER_ID,
		IMAGE_ULTRA_ID,
		IMAGE_SCL_STINKY_ID,
		IMAGE_SCL_NIKO_ID,
		IMAGE_SCL_ITCHY_ID,
		IMAGE_SCL_PREGO_ID,
		IMAGE_SCL_ZORF_ID,
		IMAGE_SCL_CLYDE_ID,
		IMAGE_SCL_VERT_ID,
		IMAGE_SCL_RUFUS_ID,
		IMAGE_SCL_MERYL_ID,
		IMAGE_SCL_WADSWORTH_ID,
		IMAGE_SCL_SEYMOUR_ID,
		IMAGE_SCL_SHRAPNEL_ID,
		IMAGE_SCL_GUMBO_ID,
		IMAGE_SCL_BLIP_ID,
		IMAGE_SCL_RHUBARB_ID,
		IMAGE_SCL_NIMBUS_ID,
		IMAGE_SCL_AMP_ID,
		IMAGE_SCL_GASH_ID,
		IMAGE_SCL_ANGIE_ID,
		IMAGE_SCL_PRESTO_ID,
		IMAGE_SCL_BRINKLEY_ID,
		IMAGE_SCL_NOSTRADAMUS_ID,
		IMAGE_SCL_STANLEY_ID,
		IMAGE_SCL_WALTER_ID,
		IMAGE_SCL_OSCAR_ID,
		IMAGE_SCL_GRUBBER_ID,
		IMAGE_SCL_STARCATCHER_ID,
		IMAGE_SCL_GEKKO_ID,
		IMAGE_SCL_BREEDER_ID,
		IMAGE_SCL_ULTRA_ID,
		SOUND_AWOOGA_ID,
		SOUND_START_ID = SOUND_AWOOGA_ID,
		SOUND_APPLAUSE_ID,
		SOUND_BABY_ID,
		SOUND_BONUSCOUNT_ID,
		SOUND_TONE_ID,
		SOUND_TONELO_ID,
		SOUND_TONEHI_ID,
		SOUND_TONESUPERHI_ID,
		SOUND_PRIMALSCREAM_ID,
		SOUND_BONUSCOLLECT_ID,
		SOUND_BUBBLES_ID,
		SOUND_BUY_ID,
		SOUND_BUZZER_ID,
		SOUND_CHOMP_ID,
		SOUND_CHOMP2_ID,
		SOUND_CROWNED_ID,
		SOUND_DIAMOND_ID,
		SOUND_DIE_ID,
		SOUND_DROPFOOD_ID,
		SOUND_EEL1_ID,
		SOUND_EEL2_ID,
		SOUND_EEL3_ID,
		SOUND_EVILLAFF_ID,
		SOUND_EXPLODE_ID,
		SOUND_EXPLOSION1_ID,
		SOUND_EXPLOSION4_ID,
		SOUND_FART_ID,
		SOUND_FART2_ID,
		SOUND_GROW_ID,
		SOUND_GUFFAW_ID,
		SOUND_HATCH_ID,
		SOUND_HEAL_ID,
		SOUND_HIT_ID,
		SOUND_INTERFER_ID,
		SOUND_MISSLE_ID,
		SOUND_NIKOOPEN_ID,
		SOUND_NIKOCLOSE_ID,
		SOUND_PEARL_ID,
		SOUND_POINTS_ID,
		SOUND_POINTS2_ID,
		SOUND_POINTS3_ID,
		SOUND_POINTS4_ID,
		SOUND_PUNCH_ID,
		SOUND_RATTLE_ID,
		SOUND_RICOCHET_ID,
		SOUND_ROAR_ID,
		SOUND_ROAR2_ID,
		SOUND_ROAR3_ID,
		SOUND_SFX_ID,
		SOUND_SING_ID,
		SOUND_SLURP_ID,
		SOUND_SLURP2_ID,
		SOUND_SLURP3_ID,
		SOUND_SNEEZE_ID,
		SOUND_SONAR_ID,
		SOUND_SPLASH_ID,
		SOUND_SPLASH2_ID,
		SOUND_SPLASH3_ID,
		SOUND_SPLASHBIG_ID,
		SOUND_TAPGLASS_ID,
		SOUND_TREASURE_ID,
		SOUND_UNLEASH_ID,
		SOUND_ZAP_ID,
		SOUND_ZZAM_ID,
		SOUND_END_ID = SOUND_ZZAM_ID,
		RESOURCE_ID_MAX
	};

	Image* GetImageById(int theId);
	Font* GetFontById(int theId);
	int GetSoundById(int theId);

	Image*& GetImageRefById(int theId);
	Font*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);

	ResourceId GetIdByImage(Image* theImage);
	ResourceId GetIdByFont(Font* theFont);
	ResourceId GetIdBySound(int theSound);
	const char* GetStringIdById(int theId);
	ResourceId GetIdByStringId(const char* theStringId);

} // namespace Sexy


#endif
